/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Supplier;

import Business.AreYouHungrySystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Order.CustomerOrder;
import Business.Order.MenuOrder;
import Business.Order.Order;
import Business.Order.RequestOrder;
import Business.Order.TruckDriverOrder;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Interface.Customer.CustomerRankJPanel;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SS
 */
public class TruckSupplyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TruckSupplyJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private AreYouHungrySystem system;
    
    private DB4OUtil db4OUtil = DB4OUtil.getInstance();
    public TruckSupplyJPanel(JPanel userProcessContainer, UserAccount userAccount, AreYouHungrySystem system) {
        initComponents();
         this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.system = system;
      
                valueLabel.setText(userAccount.toString());

     populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        Network inNetwork = null;
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        for(Network network : system.getNetworkList()){
            inNetwork = network;
        }
        for(Enterprise outEnterprise : inNetwork.getEnterpriseDirectory().getEnterpriseList()){
            if(outEnterprise.getEnterpriseType().toString().equals("Resturant")){
                inEnterprise = outEnterprise;
            }
        }
        
        for(Organization outOrganization: inEnterprise.getOrganizationDirectory().getOrganizationList()){
            //System.out.println(outOrganization.getName());
            if(outOrganization.getName().equals("Resturant Name")){
                inOrganization = outOrganization;
            }
        }
        
        //userAccount.setOrderDirectory(new OrderDirectory());
        for (UserAccount outUserAccount : inOrganization.getUserAccountDirectory().getUserAccountList()){
            for(Order order : outUserAccount.getOrderDirectory().getOrderList()){
                Object[] row = new Object[4];
            
                row[0] = ((MenuOrder) order);
                row[1] = ((MenuOrder) order).getResName();
                if(((MenuOrder) order).getStatus()==1)
                {
                   row[2] = "Waiting for truck driver";  
                }
                else if(((MenuOrder) order).getStatus()==2)
                {
                   row[2]="Truck driver on the way"; 
                }
               else if(((MenuOrder) order).getStatus()==3)
                {
                   row[2]="Truck driver arrived"; 
                }
                else if(((MenuOrder) order).getStatus()==-2)
            {
                row[2] = "Request rejected";
            }
                row[3] = ((MenuOrder) order).getSendDate();


                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backjButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel239 = new javax.swing.JLabel();
        jLabel240 = new javax.swing.JLabel();
        jLabel241 = new javax.swing.JLabel();
        jLabel242 = new javax.swing.JLabel();
        jLabel243 = new javax.swing.JLabel();
        jLabel244 = new javax.swing.JLabel();
        jLabel245 = new javax.swing.JLabel();
        jLabel246 = new javax.swing.JLabel();
        jLabel247 = new javax.swing.JLabel();
        jLabel248 = new javax.swing.JLabel();
        jLabel249 = new javax.swing.JLabel();
        jLabel250 = new javax.swing.JLabel();
        jLabel251 = new javax.swing.JLabel();
        jLabel252 = new javax.swing.JLabel();
        jLabel253 = new javax.swing.JLabel();
        jLabel254 = new javax.swing.JLabel();
        jLabel255 = new javax.swing.JLabel();
        jLabel256 = new javax.swing.JLabel();
        jLabel257 = new javax.swing.JLabel();
        jLabel258 = new javax.swing.JLabel();
        jLabel259 = new javax.swing.JLabel();
        jLabel260 = new javax.swing.JLabel();
        jLabel261 = new javax.swing.JLabel();
        jLabel262 = new javax.swing.JLabel();
        jLabel263 = new javax.swing.JLabel();
        jLabel264 = new javax.swing.JLabel();
        jLabel265 = new javax.swing.JLabel();
        jLabel266 = new javax.swing.JLabel();
        jLabel267 = new javax.swing.JLabel();
        jLabel268 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 167, 62));
        setLayout(null);

        backjButton1.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1);
        backjButton1.setBounds(1140, 51, 114, 42);

        jTable1.setBackground(new java.awt.Color(255, 102, 0));
        jTable1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Content", "Resturant", "Status", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(320, 230, 759, 140);

        jLabel5.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        jLabel5.setText("Resturant Request List");
        add(jLabel5);
        jLabel5.setBounds(548, 164, 296, 31);

        btnAccept.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept);
        btnAccept.setBounds(365, 400, 109, 40);

        jButton2.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jButton2.setText("Reject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(900, 400, 109, 40);

        valueLabel.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel);
        valueLabel.setBounds(320, 121, 158, 26);

        jLabel33.setFont(new java.awt.Font("Nanum Brush Script", 1, 80)); // NOI18N
        jLabel33.setText("Are You Hungry");
        add(jLabel33);
        jLabel33.setBounds(463, 0, 403, 93);

        jLabel8.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel8.setText("Take-Away Service");
        add(jLabel8);
        jLabel8.setBounds(878, 64, 155, 29);

        jLabel239.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel239.setText("h");
        add(jLabel239);
        jLabel239.setBounds(1170, 150, 19, 21);

        jLabel240.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel240.setText("h");
        add(jLabel240);
        jLabel240.setBounds(1080, 30, 19, 21);

        jLabel241.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel241.setText("h");
        add(jLabel241);
        jLabel241.setBounds(1210, 380, 19, 21);

        jLabel242.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel242.setText("h");
        add(jLabel242);
        jLabel242.setBounds(1010, 150, 19, 21);

        jLabel243.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel243.setText("h");
        add(jLabel243);
        jLabel243.setBounds(890, 560, 19, 21);

        jLabel244.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel244.setText("h");
        add(jLabel244);
        jLabel244.setBounds(1360, 110, 19, 21);

        jLabel245.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel245.setText("h");
        add(jLabel245);
        jLabel245.setBounds(1150, 300, 19, 21);

        jLabel246.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel246.setText("h");
        add(jLabel246);
        jLabel246.setBounds(120, 540, 19, 21);

        jLabel247.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel247.setText("h");
        add(jLabel247);
        jLabel247.setBounds(1320, 490, 19, 21);

        jLabel248.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel248.setText("h");
        add(jLabel248);
        jLabel248.setBounds(1100, 440, 19, 21);

        jLabel249.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel249.setText("h");
        add(jLabel249);
        jLabel249.setBounds(480, 600, 19, 21);

        jLabel250.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel250.setText("h");
        add(jLabel250);
        jLabel250.setBounds(660, 670, 19, 21);

        jLabel251.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel251.setText("h");
        add(jLabel251);
        jLabel251.setBounds(700, 440, 19, 21);

        jLabel252.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel252.setText("h");
        add(jLabel252);
        jLabel252.setBounds(180, 230, 19, 21);

        jLabel253.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel253.setText("h");
        add(jLabel253);
        jLabel253.setBounds(280, 590, 19, 21);

        jLabel254.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel254.setText("h");
        add(jLabel254);
        jLabel254.setBounds(350, 510, 19, 21);

        jLabel255.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel255.setText("h");
        add(jLabel255);
        jLabel255.setBounds(50, 320, 19, 21);

        jLabel256.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel256.setText("h");
        add(jLabel256);
        jLabel256.setBounds(70, 60, 19, 21);

        jLabel257.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel257.setText("h");
        add(jLabel257);
        jLabel257.setBounds(180, 380, 19, 21);

        jLabel258.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel258.setText("h");
        add(jLabel258);
        jLabel258.setBounds(470, 120, 19, 21);

        jLabel259.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel259.setText("h");
        add(jLabel259);
        jLabel259.setBounds(140, 130, 19, 21);

        jLabel260.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel260.setText("h");
        add(jLabel260);
        jLabel260.setBounds(50, 210, 19, 21);

        jLabel261.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel261.setText("h");
        add(jLabel261);
        jLabel261.setBounds(680, 90, 19, 21);

        jLabel262.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel262.setText("h");
        add(jLabel262);
        jLabel262.setBounds(290, 70, 19, 21);

        jLabel263.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel263.setText("h");
        add(jLabel263);
        jLabel263.setBounds(950, 680, 19, 21);

        jLabel264.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel264.setText("h");
        add(jLabel264);
        jLabel264.setBounds(710, 580, 19, 21);

        jLabel265.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel265.setText("h");
        add(jLabel265);
        jLabel265.setBounds(1360, 310, 19, 21);

        jLabel266.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel266.setText("h");
        add(jLabel266);
        jLabel266.setBounds(1230, 200, 19, 21);

        jLabel267.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel267.setText("h");
        add(jLabel267);
        jLabel267.setBounds(1290, 630, 19, 21);

        jLabel268.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel268.setText("h");
        add(jLabel268);
        jLabel268.setBounds(1090, 550, 19, 21);
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
          int selectedRow = jTable1.getSelectedRow();
        if(selectedRow>=0){
            MenuOrder order = (MenuOrder)jTable1.getValueAt(selectedRow, 0);
            if(order.getStatus() ==1){
                int selectionButton = JOptionPane.YES_NO_OPTION;
                int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to accept this request?","Warning",selectionButton);
                if(selectionResult == JOptionPane.YES_OPTION){
                    SimpleDateFormat sdf = new SimpleDateFormat();
                    sdf.applyPattern("yyyy-MM-dd HH:mm:ss a"); 
                    Date date = new Date();
                    ((MenuOrder) order).setStatus(2);
                    order.setTruck(userAccount.toString());
                    order.setSendDate(date);
                    
                    db4OUtil.storeSystem(system);
                    
                    populateTable();
                    
                    JOptionPane.showMessageDialog(null, "Request Accepted!!");
 
                   
                }
            }else{
                JOptionPane.showMessageDialog(null, "You cannot accept this request!!!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int selectedRow = jTable1.getSelectedRow();
        if(selectedRow>=0){
            MenuOrder order = (MenuOrder)jTable1.getValueAt(selectedRow, 0);
            if(order.getStatus() ==1){
                int selectionButton = JOptionPane.YES_NO_OPTION;
                int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to reject this request???","Warning",selectionButton);
                if(selectionResult == JOptionPane.YES_OPTION){
                    order.setStatus(-2);
                    populateTable();
                    db4OUtil.storeSystem(system);
                    JOptionPane.showMessageDialog(null, "You have rejected this request!!!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "You cannot Reject this request!!!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JLabel jLabel241;
    private javax.swing.JLabel jLabel242;
    private javax.swing.JLabel jLabel243;
    private javax.swing.JLabel jLabel244;
    private javax.swing.JLabel jLabel245;
    private javax.swing.JLabel jLabel246;
    private javax.swing.JLabel jLabel247;
    private javax.swing.JLabel jLabel248;
    private javax.swing.JLabel jLabel249;
    private javax.swing.JLabel jLabel250;
    private javax.swing.JLabel jLabel251;
    private javax.swing.JLabel jLabel252;
    private javax.swing.JLabel jLabel253;
    private javax.swing.JLabel jLabel254;
    private javax.swing.JLabel jLabel255;
    private javax.swing.JLabel jLabel256;
    private javax.swing.JLabel jLabel257;
    private javax.swing.JLabel jLabel258;
    private javax.swing.JLabel jLabel259;
    private javax.swing.JLabel jLabel260;
    private javax.swing.JLabel jLabel261;
    private javax.swing.JLabel jLabel262;
    private javax.swing.JLabel jLabel263;
    private javax.swing.JLabel jLabel264;
    private javax.swing.JLabel jLabel265;
    private javax.swing.JLabel jLabel266;
    private javax.swing.JLabel jLabel267;
    private javax.swing.JLabel jLabel268;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
