/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import Business.AreYouHungrySystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.AdminRole;
import Business.User.User;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tczho
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AreYouHungrySystem system;

    ManageEnterpriseAdminJPanel(JPanel userProcessContainer, AreYouHungrySystem areYouHungrySystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = areYouHungrySystem;
        
        populateTable();
        populateNetworkComboBox();
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    row[2] = userAccount.getUsername();

                    model.addRow(row);
                }
            }
        }
    }

    private void populateNetworkComboBox(){
        networkJComboBox.removeAllItems();
        
        for (Network network : system.getNetworkList()){
            networkJComboBox.addItem(network);
        }
    }
    
    private void populateEnterpriseComboBox(Network network){
        enterpriseJComboBox.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            enterpriseJComboBox.addItem(enterprise);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enterpriseJComboBox = new javax.swing.JComboBox();
        submitJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        backJButton = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 167, 62));
        jPanel1.setLayout(null);

        enterpriseJTable.setBackground(new java.awt.Color(255, 102, 0));
        enterpriseJTable.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(563, 201, 583, 132);

        jLabel1.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel1.setText("Network");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(642, 370, 86, 24);

        networkJComboBox.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(networkJComboBox);
        networkJComboBox.setBounds(934, 366, 136, 27);

        jLabel2.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel2.setText("Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(646, 478, 97, 24);

        usernameJTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel1.add(usernameJTextField);
        usernameJTextField.setBounds(934, 478, 136, 28);

        jLabel3.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel3.setText("Enterprise");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(642, 424, 101, 24);

        enterpriseJComboBox.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(enterpriseJComboBox);
        enterpriseJComboBox.setBounds(934, 423, 136, 27);

        submitJButton.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitJButton);
        submitJButton.setBounds(794, 653, 96, 45);

        jLabel4.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(646, 532, 95, 24);

        nameJTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel1.add(nameJTextField);
        nameJTextField.setBounds(932, 580, 136, 28);

        jLabel5.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel5.setText("Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(646, 586, 56, 24);

        passwordJPasswordField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel1.add(passwordJPasswordField);
        passwordJPasswordField.setBounds(934, 534, 134, 28);

        backJButton.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton);
        backJButton.setBounds(1282, 48, 97, 45);

        jLabel33.setFont(new java.awt.Font("Nanum Brush Script", 1, 80)); // NOI18N
        jLabel33.setText("Are You Hungry");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(463, 0, 403, 93);

        jLabel7.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel7.setText("Take-Away Service");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(878, 64, 155, 29);

        jLabel8.setFont(new java.awt.Font("Silom", 0, 24)); // NOI18N
        jLabel8.setText("Manage Enterprise Admin");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(692, 130, 332, 31);

        jLabel10.setFont(new java.awt.Font("Wingdings 3", 0, 36)); // NOI18N
        jLabel10.setText("c");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(821, 576, 34, 42);

        jLabel11.setFont(new java.awt.Font("Wingdings 3", 0, 36)); // NOI18N
        jLabel11.setText("c");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(821, 414, 34, 42);

        jLabel12.setFont(new java.awt.Font("Wingdings 3", 0, 36)); // NOI18N
        jLabel12.setText("c");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(821, 522, 34, 42);

        jLabel13.setFont(new java.awt.Font("Wingdings 3", 0, 36)); // NOI18N
        jLabel13.setText("c");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(821, 360, 34, 42);

        jLabel9.setFont(new java.awt.Font("Wingdings 3", 0, 36)); // NOI18N
        jLabel9.setText("c");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(821, 468, 34, 42);

        jLabel43.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel43.setText("h");
        jPanel1.add(jLabel43);
        jLabel43.setBounds(1130, 60, 19, 21);

        jLabel44.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel44.setText("h");
        jPanel1.add(jLabel44);
        jLabel44.setBounds(1300, 230, 19, 21);

        jLabel45.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel45.setText("h");
        jPanel1.add(jLabel45);
        jLabel45.setBounds(1150, 510, 19, 21);

        jLabel46.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel46.setText("h");
        jPanel1.add(jLabel46);
        jLabel46.setBounds(1250, 310, 19, 21);

        jLabel47.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel47.setText("h");
        jPanel1.add(jLabel47);
        jLabel47.setBounds(1360, 490, 19, 21);

        jLabel48.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel48.setText("h");
        jPanel1.add(jLabel48);
        jLabel48.setBounds(760, 790, 19, 21);

        jLabel49.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel49.setText("h");
        jPanel1.add(jLabel49);
        jLabel49.setBounds(1310, 380, 19, 21);

        jLabel50.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel50.setText("h");
        jPanel1.add(jLabel50);
        jLabel50.setBounds(1340, 780, 19, 21);

        jLabel51.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel51.setText("h");
        jPanel1.add(jLabel51);
        jLabel51.setBounds(1250, 530, 19, 21);

        jLabel52.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel52.setText("h");
        jPanel1.add(jLabel52);
        jLabel52.setBounds(470, 480, 19, 21);

        jLabel53.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel53.setText("h");
        jPanel1.add(jLabel53);
        jLabel53.setBounds(1130, 720, 19, 21);

        jLabel54.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel54.setText("h");
        jPanel1.add(jLabel54);
        jLabel54.setBounds(390, 330, 19, 21);

        jLabel55.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel55.setText("h");
        jPanel1.add(jLabel55);
        jLabel55.setBounds(630, 700, 19, 21);

        jLabel56.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel56.setText("h");
        jPanel1.add(jLabel56);
        jLabel56.setBounds(490, 560, 19, 21);

        jLabel57.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel57.setText("h");
        jPanel1.add(jLabel57);
        jLabel57.setBounds(140, 610, 19, 21);

        jLabel58.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel58.setText("h");
        jPanel1.add(jLabel58);
        jLabel58.setBounds(50, 490, 19, 21);

        jLabel59.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel59.setText("h");
        jPanel1.add(jLabel59);
        jLabel59.setBounds(130, 110, 19, 21);

        jLabel60.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel60.setText("h");
        jPanel1.add(jLabel60);
        jLabel60.setBounds(350, 470, 19, 21);

        jLabel61.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel61.setText("h");
        jPanel1.add(jLabel61);
        jLabel61.setBounds(610, 100, 19, 21);

        jLabel62.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel62.setText("h");
        jPanel1.add(jLabel62);
        jLabel62.setBounds(420, 180, 19, 21);

        jLabel63.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel63.setText("h");
        jPanel1.add(jLabel63);
        jLabel63.setBounds(160, 270, 19, 21);

        jLabel64.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel64.setText("h");
        jPanel1.add(jLabel64);
        jLabel64.setBounds(340, 60, 19, 21);

        jLabel65.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel65.setText("h");
        jPanel1.add(jLabel65);
        jLabel65.setBounds(320, 300, 19, 21);

        jLabel66.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel66.setText("h");
        jPanel1.add(jLabel66);
        jLabel66.setBounds(140, 400, 19, 21);

        jLabel67.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel67.setText("h");
        jPanel1.add(jLabel67);
        jLabel67.setBounds(90, 750, 19, 21);

        jLabel68.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel68.setText("h");
        jPanel1.add(jLabel68);
        jLabel68.setBounds(290, 800, 19, 21);

        jLabel69.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel69.setText("h");
        jPanel1.add(jLabel69);
        jLabel69.setBounds(520, 760, 19, 21);

        jLabel70.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel70.setText("h");
        jPanel1.add(jLabel70);
        jLabel70.setBounds(360, 650, 19, 21);

        jLabel71.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel71.setText("h");
        jPanel1.add(jLabel71);
        jLabel71.setBounds(1380, 130, 19, 21);

        jLabel72.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel72.setText("h");
        jPanel1.add(jLabel72);
        jLabel72.setBounds(1220, 180, 19, 21);

        jLabel73.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel73.setText("h");
        jPanel1.add(jLabel73);
        jLabel73.setBounds(1010, 800, 19, 21);

        jLabel74.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel74.setText("h");
        jPanel1.add(jLabel74);
        jLabel74.setBounds(1300, 670, 19, 21);

        jLabel75.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel75.setText("h");
        jPanel1.add(jLabel75);
        jLabel75.setBounds(960, 720, 19, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1447, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 867, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed

        Network network = (Network) networkJComboBox.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox(network);
        }

    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();

        String username = usernameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        String name = nameJTextField.getText();
        
        usernameJTextField.setBorder(new LineBorder(new Color(128,128,128)));
        passwordJPasswordField.setBorder(new LineBorder(new Color(128,128,128)));
        nameJTextField.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel2.setForeground(Color.BLACK);
        jLabel4.setForeground(Color.BLACK);
        jLabel5.setForeground(Color.BLACK);

         if(username==null||username.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Username cannot be empty!");
            usernameJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel2.setForeground(Color.RED);
            return;
        }
          if(password==null||password.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Password cannot be empty!");
            passwordJPasswordField.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel4.setForeground(Color.RED);
            return;
        }
           if(name==null||name.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Name cannot be empty!");
            nameJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel5.setForeground(Color.RED);
            return;
        }
           
        for(UserAccount account1 : enterprise.getUserAccountDirectory().getUserAccountList()){
            if(account1.getUsername().equals(username) ){
            JOptionPane.showMessageDialog(null,"UserName Already exists!");
            usernameJTextField.setText("");
            passwordJPasswordField.setText("");
            nameJTextField.setText("");
            usernameJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel2.setForeground(Color.RED);
            return;
            }
        }
        User user = enterprise.getUserDirectory().createUser(name);
        
        UserAccount account = enterprise.getUserAccountDirectory().createUserAcount(username, password, new AdminRole());
        populateTable();
        
        usernameJTextField.setText("");
        passwordJPasswordField.setText("");
        nameJTextField.setText("");
        

    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AdminJPanel sysAdminwjp = (AdminJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
