/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.AreYouHungrySystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Order.CustomerOrder;
import Business.Order.Order;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tczho
 */
public class CustomerJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private AreYouHungrySystem system;
    private DB4OUtil db4OUtil = DB4OUtil.getInstance();
    
    /**
     * Creates new form CustomerJPanel
     */
    public CustomerJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount, AreYouHungrySystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.system = system;
        
        
        populateTable();
    
        
    }
    
   
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) orderHistoryTBL.getModel();
        model.setRowCount(0);
       
        for (Order order : userAccount.getOrderDirectory().getOrderList()){
            Object[] row = new Object[7];
            
            row[0] = ((CustomerOrder) order);
            row[1] = order.getOrderStartDate();
            row[2] = order.getOrderContent();
            row[3] = ((CustomerOrder) order).getTotalPrice();
            
            if(order.getStatus() == 1){
                row[4] = "Resturant has not taken your order";
            }else if(order.getStatus() == 2){
                row[4] = "Resturant has taken your order, waiting for deliveryman";
            }else if(order.getStatus() == 3){
                row[4] = "Your order has been delivered";
            }else if(order.getStatus() == 4){
                row[4] = "Your order has been completed";
            }else if(order.getStatus() == -2){
                row[4] = "Resturant has rejected your order";
            }
            if(order.getReceiver() != null){
                row[5] = order.getReceiver();
            }
            row[6] = order.getOrderCompleteDate();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderHistoryTBL = new javax.swing.JTable();
        ConfirmBTN = new javax.swing.JButton();
        NewOrderBTN = new javax.swing.JButton();
        RefreshBTN = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 167, 62));
        setLayout(null);

        orderHistoryTBL.setBackground(new java.awt.Color(255, 102, 0));
        orderHistoryTBL.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        orderHistoryTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Resturant Name", "Order Date", "Dishes", "Total Price", "Order Status", "Deliverman", "Order complete Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderHistoryTBL);

        add(jScrollPane1);
        jScrollPane1.setBounds(311, 222, 899, 134);

        ConfirmBTN.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        ConfirmBTN.setText("Delivery Confirmation");
        ConfirmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBTNActionPerformed(evt);
            }
        });
        add(ConfirmBTN);
        ConfirmBTN.setBounds(951, 385, 259, 50);

        NewOrderBTN.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        NewOrderBTN.setText("New Order");
        NewOrderBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewOrderBTNActionPerformed(evt);
            }
        });
        add(NewOrderBTN);
        NewOrderBTN.setBounds(951, 563, 209, 50);

        RefreshBTN.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        RefreshBTN.setText("Refresh");
        RefreshBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBTNActionPerformed(evt);
            }
        });
        add(RefreshBTN);
        RefreshBTN.setBounds(1048, 49, 102, 44);

        jLabel33.setFont(new java.awt.Font("Nanum Brush Script", 1, 80)); // NOI18N
        jLabel33.setText("Are You Hungry");
        add(jLabel33);
        jLabel33.setBounds(463, 0, 403, 93);

        jLabel8.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel8.setText("Take-Away Service");
        add(jLabel8);
        jLabel8.setBounds(878, 64, 155, 29);

        jLabel1.setFont(new java.awt.Font("Silom", 0, 24)); // NOI18N
        jLabel1.setText("Customer Order History");
        add(jLabel1);
        jLabel1.setBounds(583, 133, 335, 49);

        jLabel11.setFont(new java.awt.Font("Hannotate SC", 0, 14)); // NOI18N
        jLabel11.setText("Are You Hungry?");
        add(jLabel11);
        jLabel11.setBounds(794, 501, 106, 20);

        jLabel9.setFont(new java.awt.Font("Wingdings 3", 0, 22)); // NOI18N
        jLabel9.setText("k");
        add(jLabel9);
        jLabel9.setBounds(923, 431, 16, 26);

        jLabel10.setFont(new java.awt.Font("Hannotate SC", 0, 14)); // NOI18N
        jLabel10.setText("Current Order Has Delivered? Click Here");
        add(jLabel10);
        jLabel10.setBounds(683, 469, 256, 20);

        jLabel12.setFont(new java.awt.Font("Wingdings 3", 0, 22)); // NOI18N
        jLabel12.setText("m");
        add(jLabel12);
        jLabel12.setBounds(923, 539, 16, 26);

        jLabel63.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel63.setText("h");
        add(jLabel63);
        jLabel63.setBounds(110, 260, 19, 21);

        jLabel64.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel64.setText("h");
        add(jLabel64);
        jLabel64.setBounds(640, 90, 19, 21);

        jLabel65.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel65.setText("h");
        add(jLabel65);
        jLabel65.setBounds(60, 60, 19, 21);

        jLabel66.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel66.setText("h");
        add(jLabel66);
        jLabel66.setBounds(90, 420, 19, 21);

        jLabel67.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel67.setText("h");
        add(jLabel67);
        jLabel67.setBounds(620, 420, 19, 21);

        jLabel68.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel68.setText("h");
        add(jLabel68);
        jLabel68.setBounds(240, 140, 19, 21);

        jLabel69.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel69.setText("h");
        add(jLabel69);
        jLabel69.setBounds(370, 600, 19, 21);

        jLabel70.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel70.setText("h");
        add(jLabel70);
        jLabel70.setBounds(400, 420, 19, 21);

        jLabel71.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel71.setText("h");
        add(jLabel71);
        jLabel71.setBounds(1200, 500, 19, 21);

        jLabel72.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel72.setText("h");
        add(jLabel72);
        jLabel72.setBounds(570, 530, 19, 21);

        jLabel73.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel73.setText("h");
        add(jLabel73);
        jLabel73.setBounds(270, 700, 19, 21);

        jLabel74.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel74.setText("h");
        add(jLabel74);
        jLabel74.setBounds(130, 580, 19, 21);

        jLabel75.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel75.setText("h");
        add(jLabel75);
        jLabel75.setBounds(560, 650, 19, 21);

        jLabel76.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel76.setText("h");
        add(jLabel76);
        jLabel76.setBounds(1090, 460, 19, 21);

        jLabel77.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel77.setText("h");
        add(jLabel77);
        jLabel77.setBounds(430, 730, 19, 21);

        jLabel78.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel78.setText("h");
        add(jLabel78);
        jLabel78.setBounds(720, 570, 19, 21);

        jLabel79.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel79.setText("h");
        add(jLabel79);
        jLabel79.setBounds(860, 640, 19, 21);

        jLabel80.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel80.setText("h");
        add(jLabel80);
        jLabel80.setBounds(1210, 130, 19, 21);

        jLabel81.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel81.setText("h");
        add(jLabel81);
        jLabel81.setBounds(340, 40, 19, 21);

        jLabel82.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel82.setText("h");
        add(jLabel82);
        jLabel82.setBounds(230, 260, 19, 21);

        jLabel83.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel83.setText("h");
        add(jLabel83);
        jLabel83.setBounds(450, 150, 19, 21);

        jLabel84.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel84.setText("h");
        add(jLabel84);
        jLabel84.setBounds(1250, 270, 19, 21);

        jLabel85.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel85.setText("h");
        add(jLabel85);
        jLabel85.setBounds(990, 140, 19, 21);

        jLabel86.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel86.setText("h");
        add(jLabel86);
        jLabel86.setBounds(1230, 740, 19, 21);

        jLabel87.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel87.setText("h");
        add(jLabel87);
        jLabel87.setBounds(1040, 710, 19, 21);

        jLabel88.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel88.setText("h");
        add(jLabel88);
        jLabel88.setBounds(590, 770, 19, 21);

        jLabel89.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel89.setText("h");
        add(jLabel89);
        jLabel89.setBounds(730, 730, 19, 21);

        jLabel90.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel90.setText("h");
        add(jLabel90);
        jLabel90.setBounds(90, 770, 19, 21);

        jLabel91.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel91.setText("h");
        add(jLabel91);
        jLabel91.setBounds(240, 480, 19, 21);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBTNActionPerformed
        int selectedRow = orderHistoryTBL.getSelectedRow();
        if(selectedRow>=0){
            CustomerOrder order = (CustomerOrder)orderHistoryTBL.getValueAt(selectedRow, 0);
            if(order.getStatus() ==3){
                int selectionButton = JOptionPane.YES_NO_OPTION;
                int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure this order has reached???","Warning",selectionButton);
                if(selectionResult == JOptionPane.YES_OPTION){
                    SimpleDateFormat sdf = new SimpleDateFormat();
                    sdf.applyPattern("yyyy-MM-dd HH:mm:ss a"); 
                    Date date = new Date();
                    order.setStatus(4);
                    order.setOrderCompleteDate(date);
                    
                    db4OUtil.storeSystem(system);
                    
                    populateTable();
                    
                    CustomerRankJPanel panel = new CustomerRankJPanel(userProcessContainer, order, system);
                    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                    userProcessContainer.add("CustomerRankJPanel", panel);
                    layout.next(userProcessContainer);
                }
            }else{
                JOptionPane.showMessageDialog(null, "You cannot Confirm this Order!!!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_ConfirmBTNActionPerformed

    private void NewOrderBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewOrderBTNActionPerformed
        CustomerNewOrderJPanel panel = new CustomerNewOrderJPanel(userProcessContainer, userAccount, system);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("CustomerNewOrderJPanel", panel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_NewOrderBTNActionPerformed

    private void RefreshBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBTNActionPerformed
        populateTable();
    }//GEN-LAST:event_RefreshBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmBTN;
    private javax.swing.JButton NewOrderBTN;
    private javax.swing.JButton RefreshBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderHistoryTBL;
    // End of variables declaration//GEN-END:variables
}
