/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.AreYouHungrySystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Order.CustomerOrder;
import Business.Order.MenuOrder;
import Business.Order.Order;
import Business.Order.OrderDirectory;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tczho
 */
public class CustomerNewOrderJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private AreYouHungrySystem system;
    private Network inNetwork;
    private Enterprise inEnterprise;
    private Organization inOrganization;
    private DB4OUtil db4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form CustomerNewOrderJPanel
     */
    CustomerNewOrderJPanel(JPanel userProcessContainer, UserAccount userAccount, AreYouHungrySystem system) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        
        inNetwork = null;
        inEnterprise = null;
        inOrganization = null;
        for(Network outNetwork: system.getNetworkList()){
            if(outNetwork.getName().equals("Boston")){
                inNetwork = outNetwork;
            }
        }
        
        for(Enterprise outEnterprise: inNetwork.getEnterpriseDirectory().getEnterpriseList()){
            if(outEnterprise.getEnterpriseType().toString().equals("Resturant")){
                inEnterprise = outEnterprise;
            }
        }
        
        for(Organization outOrganization: inEnterprise.getOrganizationDirectory().getOrganizationList()){
            //System.out.println(outOrganization.getName());
            if(outOrganization.getName().equals("Resturant Name")){
                inOrganization = outOrganization;
            }
        }
        
        populateComboBox();
    }

    private void populateComboBox() {
        resturantNameComboBox.removeAllItems();
        for (UserAccount ua : inOrganization.getUserAccountDirectory().getUserAccountList()) {
            resturantNameComboBox.addItem(ua.getUsername());
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resturantNameComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        dish1JTextField = new javax.swing.JTextField();
        dish2JTextField = new javax.swing.JTextField();
        dish3JTextField = new javax.swing.JTextField();
        dish4JTextField = new javax.swing.JTextField();
        dish5JTextField = new javax.swing.JTextField();
        dish6JTextField = new javax.swing.JTextField();
        dish7JTextField = new javax.swing.JTextField();
        dish8JTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        quanity1JTextField = new javax.swing.JTextField();
        quanity3JTextField = new javax.swing.JTextField();
        quanity4JTextField = new javax.swing.JTextField();
        quanity5JTextField = new javax.swing.JTextField();
        quanity6JTextField = new javax.swing.JTextField();
        quanity7JTextField = new javax.swing.JTextField();
        quanity8JTextField = new javax.swing.JTextField();
        quanity2JTextField = new javax.swing.JTextField();
        backjButton2 = new javax.swing.JButton();
        MakeOrderBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        avgRankJLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        price2JTextField = new javax.swing.JLabel();
        price1JTextField = new javax.swing.JLabel();
        price4JTextField = new javax.swing.JLabel();
        price5JTextField = new javax.swing.JLabel();
        price8JTextField = new javax.swing.JLabel();
        price3JTextField = new javax.swing.JLabel();
        price6JTextField = new javax.swing.JLabel();
        price7JTextField = new javax.swing.JLabel();
        dish1 = new javax.swing.JLabel();
        dish2 = new javax.swing.JLabel();
        dish4 = new javax.swing.JLabel();
        dish6 = new javax.swing.JLabel();
        dish7 = new javax.swing.JLabel();
        dish3 = new javax.swing.JLabel();
        dish5 = new javax.swing.JLabel();
        dish8 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 167, 62));
        setLayout(null);

        resturantNameComboBox.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        resturantNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        resturantNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resturantNameComboBoxActionPerformed(evt);
            }
        });
        add(resturantNameComboBox);
        resturantNameComboBox.setBounds(214, 132, 174, 27);

        jLabel2.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel2.setText("Restaurant");
        add(jLabel2);
        jLabel2.setBounds(87, 131, 109, 24);

        dish1JTextField.setEditable(false);
        dish1JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(dish1JTextField);
        dish1JTextField.setBounds(445, 273, 116, 28);

        dish2JTextField.setEditable(false);
        dish2JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(dish2JTextField);
        dish2JTextField.setBounds(445, 350, 116, 28);

        dish3JTextField.setEditable(false);
        dish3JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(dish3JTextField);
        dish3JTextField.setBounds(445, 409, 116, 28);

        dish4JTextField.setEditable(false);
        dish4JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(dish4JTextField);
        dish4JTextField.setBounds(445, 470, 116, 28);

        dish5JTextField.setEditable(false);
        dish5JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dish5JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish5JTextFieldActionPerformed(evt);
            }
        });
        add(dish5JTextField);
        dish5JTextField.setBounds(445, 531, 116, 28);

        dish6JTextField.setEditable(false);
        dish6JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dish6JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish6JTextFieldActionPerformed(evt);
            }
        });
        add(dish6JTextField);
        dish6JTextField.setBounds(445, 587, 116, 28);

        dish7JTextField.setEditable(false);
        dish7JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dish7JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish7JTextFieldActionPerformed(evt);
            }
        });
        add(dish7JTextField);
        dish7JTextField.setBounds(445, 648, 116, 28);

        dish8JTextField.setEditable(false);
        dish8JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dish8JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish8JTextFieldActionPerformed(evt);
            }
        });
        add(dish8JTextField);
        dish8JTextField.setBounds(445, 709, 116, 28);

        jLabel4.setFont(new java.awt.Font("Nanum Brush Script", 0, 36)); // NOI18N
        jLabel4.setText("Menu");
        add(jLabel4);
        jLabel4.setBounds(471, 218, 75, 28);

        jLabel3.setFont(new java.awt.Font("Nanum Brush Script", 0, 36)); // NOI18N
        jLabel3.setText("Quantity");
        add(jLabel3);
        jLabel3.setBounds(932, 211, 104, 43);

        quanity1JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(quanity1JTextField);
        quanity1JTextField.setBounds(967, 272, 48, 28);

        quanity3JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(quanity3JTextField);
        quanity3JTextField.setBounds(967, 409, 48, 28);

        quanity4JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(quanity4JTextField);
        quanity4JTextField.setBounds(967, 472, 48, 26);

        quanity5JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(quanity5JTextField);
        quanity5JTextField.setBounds(967, 531, 48, 28);

        quanity6JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        quanity6JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanity6JTextFieldActionPerformed(evt);
            }
        });
        add(quanity6JTextField);
        quanity6JTextField.setBounds(967, 584, 48, 28);

        quanity7JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(quanity7JTextField);
        quanity7JTextField.setBounds(967, 648, 48, 28);

        quanity8JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(quanity8JTextField);
        quanity8JTextField.setBounds(967, 709, 48, 28);

        quanity2JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(quanity2JTextField);
        quanity2JTextField.setBounds(967, 347, 48, 28);

        backjButton2.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        backjButton2.setText("<< Back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });
        add(backjButton2);
        backjButton2.setBounds(1252, 48, 114, 45);

        MakeOrderBTN.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        MakeOrderBTN.setText("Confirm");
        MakeOrderBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeOrderBTNActionPerformed(evt);
            }
        });
        add(MakeOrderBTN);
        MakeOrderBTN.setBounds(87, 692, 122, 45);

        jLabel5.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel5.setText("AVG Rank");
        add(jLabel5);
        jLabel5.setBounds(87, 177, 89, 24);

        avgRankJLabel.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        add(avgRankJLabel);
        avgRankJLabel.setBounds(226, 177, 39, 28);

        jLabel6.setFont(new java.awt.Font("Nanum Brush Script", 0, 36)); // NOI18N
        jLabel6.setText("Price");
        add(jLabel6);
        jLabel6.setBounds(664, 211, 60, 43);

        price2JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price2JTextField);
        price2JTextField.setBounds(664, 347, 95, 32);

        price1JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price1JTextField);
        price1JTextField.setBounds(664, 273, 95, 28);

        price4JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price4JTextField);
        price4JTextField.setBounds(664, 478, 95, 20);

        price5JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price5JTextField);
        price5JTextField.setBounds(664, 538, 95, 21);

        price8JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price8JTextField);
        price8JTextField.setBounds(664, 709, 95, 28);

        price3JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price3JTextField);
        price3JTextField.setBounds(664, 413, 95, 24);

        price6JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price6JTextField);
        price6JTextField.setBounds(664, 584, 95, 28);

        price7JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price7JTextField);
        price7JTextField.setBounds(664, 648, 95, 28);
        add(dish1);
        dish1.setBounds(1250, 224, 116, 98);
        add(dish2);
        dish2.setBounds(1250, 352, 116, 98);
        add(dish4);
        dish4.setBounds(1250, 615, 116, 98);
        add(dish6);
        dish6.setBounds(1663, 352, 116, 98);
        add(dish7);
        dish7.setBounds(1663, 480, 116, 98);
        add(dish3);
        dish3.setBounds(1250, 480, 116, 98);
        add(dish5);
        dish5.setBounds(1663, 224, 116, 98);
        add(dish8);
        dish8.setBounds(1663, 614, 116, 98);

        jLabel33.setFont(new java.awt.Font("Nanum Brush Script", 1, 80)); // NOI18N
        jLabel33.setText("Are You Hungry");
        add(jLabel33);
        jLabel33.setBounds(463, 0, 403, 93);

        jLabel7.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel7.setText("Take-Away Service");
        add(jLabel7);
        jLabel7.setBounds(878, 64, 155, 29);

        jLabel1.setFont(new java.awt.Font("Silom", 0, 24)); // NOI18N
        jLabel1.setText("Make a  order");
        add(jLabel1);
        jLabel1.setBounds(722, 126, 178, 31);

        jLabel8.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel8.setText("NO.1");
        add(jLabel8);
        jLabel8.setBounds(1202, 222, 33, 29);

        jLabel9.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel9.setText("NO.2");
        add(jLabel9);
        jLabel9.setBounds(391, 347, 36, 29);

        jLabel10.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel10.setText("NO.3");
        add(jLabel10);
        jLabel10.setBounds(1196, 480, 36, 29);

        jLabel11.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel11.setText("NO.4");
        add(jLabel11);
        jLabel11.setBounds(387, 467, 40, 29);

        jLabel12.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel12.setText("NO.5");
        add(jLabel12);
        jLabel12.setBounds(391, 528, 36, 29);

        jLabel13.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel13.setText("NO.6");
        add(jLabel13);
        jLabel13.setBounds(391, 584, 36, 29);

        jLabel14.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel14.setText("NO.7");
        add(jLabel14);
        jLabel14.setBounds(389, 645, 38, 29);

        jLabel15.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel15.setText("NO.8");
        add(jLabel15);
        jLabel15.setBounds(392, 706, 35, 29);

        jLabel16.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel16.setText("NO.1");
        add(jLabel16);
        jLabel16.setBounds(391, 272, 33, 29);

        jLabel17.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel17.setText("NO.2");
        add(jLabel17);
        jLabel17.setBounds(1198, 352, 36, 29);

        jLabel18.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel18.setText("NO.3");
        add(jLabel18);
        jLabel18.setBounds(391, 408, 36, 29);

        jLabel19.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel19.setText("NO.4");
        add(jLabel19);
        jLabel19.setBounds(1198, 615, 40, 29);

        jLabel20.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel20.setText("NO.5");
        add(jLabel20);
        jLabel20.setBounds(1615, 224, 36, 29);

        jLabel21.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel21.setText("NO.6");
        add(jLabel21);
        jLabel21.setBounds(1615, 352, 36, 29);

        jLabel22.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel22.setText("NO.7");
        add(jLabel22);
        jLabel22.setBounds(1613, 480, 38, 29);

        jLabel23.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel23.setText("NO.8");
        add(jLabel23);
        jLabel23.setBounds(1616, 606, 35, 29);

        jLabel65.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel65.setText("h");
        add(jLabel65);
        jLabel65.setBounds(100, 570, 19, 21);

        jLabel66.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel66.setText("h");
        add(jLabel66);
        jLabel66.setBounds(420, 200, 19, 21);

        jLabel67.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel67.setText("h");
        add(jLabel67);
        jLabel67.setBounds(120, 260, 19, 21);

        jLabel68.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel68.setText("h");
        add(jLabel68);
        jLabel68.setBounds(220, 60, 19, 21);

        jLabel69.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel69.setText("h");
        add(jLabel69);
        jLabel69.setBounds(1060, 120, 19, 21);

        jLabel70.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel70.setText("h");
        add(jLabel70);
        jLabel70.setBounds(50, 320, 19, 21);

        jLabel71.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel71.setText("h");
        add(jLabel71);
        jLabel71.setBounds(270, 600, 19, 21);

        jLabel72.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel72.setText("h");
        add(jLabel72);
        jLabel72.setBounds(270, 450, 19, 21);

        jLabel73.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel73.setText("h");
        add(jLabel73);
        jLabel73.setBounds(120, 420, 19, 21);

        jLabel74.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel74.setText("h");
        add(jLabel74);
        jLabel74.setBounds(60, 70, 19, 21);

        jLabel75.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel75.setText("h");
        add(jLabel75);
        jLabel75.setBounds(260, 200, 19, 21);

        jLabel76.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel76.setText("h");
        add(jLabel76);
        jLabel76.setBounds(1570, 50, 19, 21);

        jLabel77.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel77.setText("h");
        add(jLabel77);
        jLabel77.setBounds(600, 130, 19, 21);

        jLabel78.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel78.setText("h");
        add(jLabel78);
        jLabel78.setBounds(1800, 130, 19, 21);

        jLabel79.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel79.setText("h");
        add(jLabel79);
        jLabel79.setBounds(1220, 110, 19, 21);

        jLabel80.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel80.setText("h");
        add(jLabel80);
        jLabel80.setBounds(1360, 300, 19, 21);

        jLabel81.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel81.setText("h");
        add(jLabel81);
        jLabel81.setBounds(1430, 110, 19, 21);

        jLabel82.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel82.setText("h");
        add(jLabel82);
        jLabel82.setBounds(1890, 460, 19, 21);

        jLabel83.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel83.setText("h");
        add(jLabel83);
        jLabel83.setBounds(1880, 730, 19, 21);

        jLabel84.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel84.setText("h");
        add(jLabel84);
        jLabel84.setBounds(1810, 270, 19, 21);

        jLabel85.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel85.setText("h");
        add(jLabel85);
        jLabel85.setBounds(1400, 510, 19, 21);

        jLabel86.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel86.setText("h");
        add(jLabel86);
        jLabel86.setBounds(1870, 590, 19, 21);

        jLabel87.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel87.setText("h");
        add(jLabel87);
        jLabel87.setBounds(740, 780, 19, 21);

        jLabel88.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel88.setText("h");
        add(jLabel88);
        jLabel88.setBounds(1680, 770, 19, 21);

        jLabel89.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel89.setText("h");
        add(jLabel89);
        jLabel89.setBounds(1290, 950, 19, 21);

        jLabel90.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel90.setText("h");
        add(jLabel90);
        jLabel90.setBounds(1240, 810, 19, 21);

        jLabel91.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel91.setText("h");
        add(jLabel91);
        jLabel91.setBounds(860, 830, 19, 21);

        jLabel92.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel92.setText("h");
        add(jLabel92);
        jLabel92.setBounds(780, 650, 19, 21);

        jLabel93.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel93.setText("h");
        add(jLabel93);
        jLabel93.setBounds(1080, 930, 19, 21);

        jLabel94.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel94.setText("h");
        add(jLabel94);
        jLabel94.setBounds(840, 550, 19, 21);

        jLabel95.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel95.setText("h");
        add(jLabel95);
        jLabel95.setBounds(730, 450, 19, 21);

        jLabel96.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel96.setText("h");
        add(jLabel96);
        jLabel96.setBounds(880, 690, 19, 21);

        jLabel97.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel97.setText("h");
        add(jLabel97);
        jLabel97.setBounds(410, 790, 19, 21);

        jLabel98.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel98.setText("h");
        add(jLabel98);
        jLabel98.setBounds(580, 860, 19, 21);

        jLabel99.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel99.setText("h");
        add(jLabel99);
        jLabel99.setBounds(1100, 370, 19, 21);

        jLabel100.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel100.setText("h");
        add(jLabel100);
        jLabel100.setBounds(1440, 700, 19, 21);

        jLabel101.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel101.setText("h");
        add(jLabel101);
        jLabel101.setBounds(1480, 240, 19, 21);

        jLabel102.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel102.setText("h");
        add(jLabel102);
        jLabel102.setBounds(1710, 450, 19, 21);

        jLabel103.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel103.setText("h");
        add(jLabel103);
        jLabel103.setBounds(1080, 660, 19, 21);

        jLabel104.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel104.setText("h");
        add(jLabel104);
        jLabel104.setBounds(1310, 460, 19, 21);

        jLabel105.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel105.setText("h");
        add(jLabel105);
        jLabel105.setBounds(660, 360, 19, 21);

        jLabel106.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel106.setText("h");
        add(jLabel106);
        jLabel106.setBounds(590, 580, 19, 21);
    }// </editor-fold>//GEN-END:initComponents

    private void resturantNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resturantNameComboBoxActionPerformed
        Integer number = 0;
        Integer totalRank = 0;
        String resturantName = "";
        ArrayList<String> menuList = new ArrayList<String>();
        if(resturantNameComboBox.getSelectedItem() != null){
            resturantName = resturantNameComboBox.getSelectedItem().toString();
            for(UserAccount ua : inOrganization.getUserAccountDirectory().getUserAccountList()){
                if(ua.getUsername().equals(resturantName)){
                    for(Order menuOrder : ua.getOrderDirectory().getOrderList()){
                        dish1JTextField.setText(((MenuOrder) menuOrder).getDish1());
                        dish2JTextField.setText(((MenuOrder) menuOrder).getDish2());
                        dish3JTextField.setText(((MenuOrder) menuOrder).getDish3());
                        dish4JTextField.setText(((MenuOrder) menuOrder).getDish4());
                        dish5JTextField.setText(((MenuOrder) menuOrder).getDish5());
                        dish6JTextField.setText(((MenuOrder) menuOrder).getDish6());
                        dish7JTextField.setText(((MenuOrder) menuOrder).getDish7());
                        dish8JTextField.setText(((MenuOrder) menuOrder).getDish8());
                        
                        price1JTextField.setText(String.valueOf(((MenuOrder) menuOrder).getPrice1()));
                        price2JTextField.setText(String.valueOf(((MenuOrder) menuOrder).getPrice2()));
                        price3JTextField.setText(String.valueOf(((MenuOrder) menuOrder).getPrice3()));
                        price4JTextField.setText(String.valueOf(((MenuOrder) menuOrder).getPrice4()));
                        price5JTextField.setText(String.valueOf(((MenuOrder) menuOrder).getPrice5()));
                        price6JTextField.setText(String.valueOf(((MenuOrder) menuOrder).getPrice6()));
                        price7JTextField.setText(String.valueOf(((MenuOrder) menuOrder).getPrice7()));
                        price8JTextField.setText(String.valueOf(((MenuOrder) menuOrder).getPrice8()));
                        
                        dish1.setIcon( ((MenuOrder) menuOrder).getDish11());
                        dish2.setIcon( ((MenuOrder) menuOrder).getDish12());
                        dish3.setIcon( ((MenuOrder) menuOrder).getDish13());
                        dish4.setIcon( ((MenuOrder) menuOrder).getDish14());
                        dish5.setIcon( ((MenuOrder) menuOrder).getDish15());
                        dish6.setIcon( ((MenuOrder) menuOrder).getDish16());
                        dish7.setIcon( ((MenuOrder) menuOrder).getDish17());
                        dish8.setIcon( ((MenuOrder) menuOrder).getDish18());

                    }
                }
            }
            for(Network outNetwork: system.getNetworkList()){
                if(outNetwork.getName().equals("Boston")){
                    inNetwork = outNetwork;
                }
            }

            for(Enterprise outEnterprise: inNetwork.getEnterpriseDirectory().getEnterpriseList()){
                if(outEnterprise.getEnterpriseType().toString().equals("Customer")){
                    inEnterprise = outEnterprise;
                }
            }

            for(UserAccount outUserAccount: inEnterprise.getUserAccountDirectory().getUserAccountList()){
                for(Order outOrder : outUserAccount.getOrderDirectory().getOrderList()){
                    if(((CustomerOrder) outOrder).getResturantName().equals(resturantName)){
                        number++;
                        totalRank += ((CustomerOrder) outOrder).getRank();
                    }
                }
            }
            
            if(number != 0){
                Integer avgRank = totalRank/number;
                avgRankJLabel.setText(avgRank.toString());
            }
        }
    }//GEN-LAST:event_resturantNameComboBoxActionPerformed

    private void dish5JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish5JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dish5JTextFieldActionPerformed

    private void dish6JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish6JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dish6JTextFieldActionPerformed

    private void dish7JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish7JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dish7JTextFieldActionPerformed

    private void dish8JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish8JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dish8JTextFieldActionPerformed

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton2ActionPerformed

    private void MakeOrderBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeOrderBTNActionPerformed
        String orderContent = "";
        Double totalPrice = 0.00;
        if(!quanity1JTextField.getText().equals("")&&!dish1JTextField.getText().equals("")){
            String dish1 = dish1JTextField.getText();
            String quanity1 = quanity1JTextField.getText();
            orderContent += dish1 + "*" + quanity1;
            totalPrice += Integer.parseInt(quanity1) * Double.parseDouble(price1JTextField.getText());
        }
        if(!quanity2JTextField.getText().equals("")&&!dish2JTextField.getText().equals("")){
            String dish2 = dish2JTextField.getText();
            String quanity2 = quanity2JTextField.getText();
            orderContent += " " + dish2 + "*" + quanity2;
            totalPrice += Integer.parseInt(quanity2) * Double.parseDouble(price2JTextField.getText());
        }
        if(!quanity3JTextField.getText().equals("")&&!dish3JTextField.getText().equals("")){
            String dish3 = dish3JTextField.getText();
            String quanity3 = quanity3JTextField.getText();
            orderContent += " " + dish3 + "*" + quanity3;
            totalPrice += Integer.parseInt(quanity3) * Double.parseDouble(price3JTextField.getText());
        }
        if(!quanity4JTextField.getText().equals("")&&!dish4JTextField.getText().equals("")){
            String dish4 = dish4JTextField.getText();
            String quanity4 = quanity4JTextField.getText();
            orderContent += " " + dish4 + "*" + quanity4;
            totalPrice += Integer.parseInt(quanity4) * Double.parseDouble(price4JTextField.getText());
        }
        if(!quanity5JTextField.getText().equals("")&&!dish5JTextField.getText().equals("")){
            String dish5 = dish5JTextField.getText();
            String quanity5 = quanity5JTextField.getText();
            orderContent += " " + dish5 + "*" + quanity5;
            totalPrice += Integer.parseInt(quanity5) * Double.parseDouble(price5JTextField.getText());
        }
        if(!quanity6JTextField.getText().equals("")&&!dish6JTextField.getText().equals("")){
            String dish6 = dish6JTextField.getText();
            String quanity6 = quanity6JTextField.getText();
            orderContent += " " + dish6 + "*" + quanity6;
            totalPrice += Integer.parseInt(quanity6) * Double.parseDouble(price6JTextField.getText());
        }
        if(!quanity7JTextField.getText().equals("")&&!dish7JTextField.getText().equals("")){
            String dish7 = dish7JTextField.getText();
            String quanity7 = quanity7JTextField.getText();
            orderContent += " " + dish7 + "*" + quanity7;
            totalPrice += Integer.parseInt(quanity7) * Double.parseDouble(price7JTextField.getText());
        }
        if(!quanity8JTextField.getText().equals("")&&!dish8JTextField.getText().equals("")){
            String dish8 = dish8JTextField.getText();
            String quanity8 = quanity8JTextField.getText();
            orderContent += " " + dish8 + "*" + quanity8;
            totalPrice += Integer.parseInt(quanity8) * Double.parseDouble(price8JTextField.getText());
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat();
        sdf.applyPattern("yyyy-MM-dd HH:mm:ss a"); 
        Date date = new Date();
        
        if(totalPrice==0.0)
        {  
        JOptionPane.showMessageDialog(null, "Failed!!");
        return;
        }
        
        CustomerOrder order = new CustomerOrder();
        order.setResturantName(resturantNameComboBox.getSelectedItem().toString());
        order.setStatus(1);
        order.setSender(userAccount);
        order.setOrderContent(orderContent);
        order.setOrderStartDate(date);
        order.setTotalPrice(totalPrice);
        
        userAccount.getOrderDirectory().getOrderList().add(order);
        
        db4OUtil.storeSystem(system);
        
        JOptionPane.showMessageDialog(null, "You have successfully make an order!!!");
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_MakeOrderBTNActionPerformed

    private void quanity6JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanity6JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quanity6JTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MakeOrderBTN;
    private javax.swing.JLabel avgRankJLabel;
    private javax.swing.JButton backjButton2;
    private javax.swing.JLabel dish1;
    private javax.swing.JTextField dish1JTextField;
    private javax.swing.JLabel dish2;
    private javax.swing.JTextField dish2JTextField;
    private javax.swing.JLabel dish3;
    private javax.swing.JTextField dish3JTextField;
    private javax.swing.JLabel dish4;
    private javax.swing.JTextField dish4JTextField;
    private javax.swing.JLabel dish5;
    private javax.swing.JTextField dish5JTextField;
    private javax.swing.JLabel dish6;
    private javax.swing.JTextField dish6JTextField;
    private javax.swing.JLabel dish7;
    private javax.swing.JTextField dish7JTextField;
    private javax.swing.JLabel dish8;
    private javax.swing.JTextField dish8JTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JLabel price1JTextField;
    private javax.swing.JLabel price2JTextField;
    private javax.swing.JLabel price3JTextField;
    private javax.swing.JLabel price4JTextField;
    private javax.swing.JLabel price5JTextField;
    private javax.swing.JLabel price6JTextField;
    private javax.swing.JLabel price7JTextField;
    private javax.swing.JLabel price8JTextField;
    private javax.swing.JTextField quanity1JTextField;
    private javax.swing.JTextField quanity2JTextField;
    private javax.swing.JTextField quanity3JTextField;
    private javax.swing.JTextField quanity4JTextField;
    private javax.swing.JTextField quanity5JTextField;
    private javax.swing.JTextField quanity6JTextField;
    private javax.swing.JTextField quanity7JTextField;
    private javax.swing.JTextField quanity8JTextField;
    private javax.swing.JComboBox<String> resturantNameComboBox;
    // End of variables declaration//GEN-END:variables
}
