/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.AreYouHungrySystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tczho
 */
public class CustomerRegistrationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AreYouHungrySystem system;
    private DB4OUtil db4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form CustomerRegistrationJPanel
     */
    public CustomerRegistrationJPanel(JPanel jPanel2, AreYouHungrySystem system) {
        initComponents();
        this.userProcessContainer = jPanel2;
        this.system = system;
        
        populateComboBox();
        //System.out.println("1111");
    }
    
    private void populateComboBox() {
        networkJComboBox.removeAllItems();

        for (Network network : system.getNetworkList()) {
            networkJComboBox.addItem(network);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        passwordJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CreateCustomerBTN = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 167, 62));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel2.setText("City");
        add(jLabel2);
        jLabel2.setBounds(453, 206, 39, 24);

        networkJComboBox.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(networkJComboBox);
        networkJComboBox.setBounds(746, 209, 184, 27);

        jLabel3.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel3.setText("User Name");
        add(jLabel3);
        jLabel3.setBounds(453, 254, 104, 24);

        nameJTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(nameJTextField);
        nameJTextField.setBounds(746, 254, 184, 28);

        passwordJTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(passwordJTextField);
        passwordJTextField.setBounds(746, 300, 184, 28);

        jLabel4.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        add(jLabel4);
        jLabel4.setBounds(453, 304, 95, 24);

        CreateCustomerBTN.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        CreateCustomerBTN.setText("Submit");
        CreateCustomerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCustomerBTNActionPerformed(evt);
            }
        });
        add(CreateCustomerBTN);
        CreateCustomerBTN.setBounds(608, 363, 111, 45);

        jLabel33.setFont(new java.awt.Font("Nanum Brush Script", 1, 80)); // NOI18N
        jLabel33.setText("Are You Hungry");
        add(jLabel33);
        jLabel33.setBounds(463, 0, 403, 93);

        jLabel7.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel7.setText("Take-Away Service");
        add(jLabel7);
        jLabel7.setBounds(878, 64, 155, 29);

        jLabel5.setFont(new java.awt.Font("Silom", 0, 24)); // NOI18N
        jLabel5.setText("Customer Registration");
        add(jLabel5);
        jLabel5.setBounds(517, 133, 294, 31);

        jLabel10.setFont(new java.awt.Font("Wingdings 3", 0, 36)); // NOI18N
        jLabel10.setText("c");
        add(jLabel10);
        jLabel10.setBounds(634, 238, 34, 42);

        jLabel11.setFont(new java.awt.Font("Wingdings 3", 0, 36)); // NOI18N
        jLabel11.setText("c");
        add(jLabel11);
        jLabel11.setBounds(634, 190, 34, 42);

        jLabel12.setFont(new java.awt.Font("Wingdings 3", 0, 36)); // NOI18N
        jLabel12.setText("c");
        add(jLabel12);
        jLabel12.setBounds(634, 286, 34, 42);

        jLabel122.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel122.setText("h");
        add(jLabel122);
        jLabel122.setBounds(190, 170, 19, 20);

        jLabel123.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel123.setText("h");
        add(jLabel123);
        jLabel123.setBounds(110, 560, 19, 20);

        jLabel124.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel124.setText("h");
        add(jLabel124);
        jLabel124.setBounds(120, 290, 19, 20);

        jLabel125.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel125.setText("h");
        add(jLabel125);
        jLabel125.setBounds(80, 60, 19, 20);

        jLabel126.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel126.setText("h");
        add(jLabel126);
        jLabel126.setBounds(370, 20, 19, 20);

        jLabel127.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel127.setText("h");
        add(jLabel127);
        jLabel127.setBounds(160, 440, 19, 20);

        jLabel128.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel128.setText("h");
        add(jLabel128);
        jLabel128.setBounds(290, 260, 19, 20);

        jLabel129.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel129.setText("h");
        add(jLabel129);
        jLabel129.setBounds(1050, 140, 19, 20);

        jLabel130.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel130.setText("h");
        add(jLabel130);
        jLabel130.setBounds(290, 370, 19, 20);

        jLabel131.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel131.setText("h");
        add(jLabel131);
        jLabel131.setBounds(470, 410, 19, 20);

        jLabel132.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel132.setText("h");
        add(jLabel132);
        jLabel132.setBounds(280, 460, 19, 20);

        jLabel133.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel133.setText("h");
        add(jLabel133);
        jLabel133.setBounds(270, 560, 19, 20);

        jLabel134.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel134.setText("h");
        add(jLabel134);
        jLabel134.setBounds(150, 720, 19, 20);

        jLabel135.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel135.setText("h");
        add(jLabel135);
        jLabel135.setBounds(650, 720, 19, 20);

        jLabel136.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel136.setText("h");
        add(jLabel136);
        jLabel136.setBounds(920, 640, 19, 20);

        jLabel137.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel137.setText("h");
        add(jLabel137);
        jLabel137.setBounds(810, 360, 19, 21);

        jLabel138.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel138.setText("h");
        add(jLabel138);
        jLabel138.setBounds(1070, 230, 19, 20);

        jLabel139.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel139.setText("h");
        add(jLabel139);
        jLabel139.setBounds(1310, 580, 19, 20);

        jLabel140.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel140.setText("h");
        add(jLabel140);
        jLabel140.setBounds(1110, 380, 19, 20);

        jLabel141.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel141.setText("h");
        add(jLabel141);
        jLabel141.setBounds(1360, 220, 19, 20);

        jLabel142.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel142.setText("h");
        add(jLabel142);
        jLabel142.setBounds(1220, 290, 19, 20);

        jLabel143.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel143.setText("h");
        add(jLabel143);
        jLabel143.setBounds(1310, 40, 19, 20);

        jLabel144.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel144.setText("h");
        add(jLabel144);
        jLabel144.setBounds(1250, 170, 19, 20);

        jLabel145.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel145.setText("h");
        add(jLabel145);
        jLabel145.setBounds(380, 690, 19, 20);

        jLabel146.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel146.setText("h");
        add(jLabel146);
        jLabel146.setBounds(480, 530, 19, 20);

        jLabel147.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel147.setText("h");
        add(jLabel147);
        jLabel147.setBounds(560, 210, 19, 21);

        jLabel148.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel148.setText("h");
        add(jLabel148);
        jLabel148.setBounds(890, 500, 19, 21);

        jLabel149.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel149.setText("h");
        add(jLabel149);
        jLabel149.setBounds(1260, 420, 19, 20);

        jLabel150.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel150.setText("h");
        add(jLabel150);
        jLabel150.setBounds(1120, 590, 19, 20);

        jLabel151.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel151.setText("h");
        add(jLabel151);
        jLabel151.setBounds(680, 570, 19, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void CreateCustomerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateCustomerBTNActionPerformed
        Network network = (Network)networkJComboBox.getSelectedItem();
        String username = nameJTextField.getText();
        String password = passwordJTextField.getText();
         if(username==null||username.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Username cannot be empty!");
            return;
        }
          if(password==null||password.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Password cannot be empty!");
            return;
        }
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
//            System.out.println("1111111"+enterprise.getEnterpriseType());
//            System.out.println("2222222"+enterprise.getEnterpriseType().Customer);
            if(enterprise.getEnterpriseType().toString().equals("Customer")){
                //System.out.println("333333"+enterprise.getEnterpriseType());
            for(UserAccount account1 : enterprise.getUserAccountDirectory().getUserAccountList()){
            if(account1.getUsername().equals(username) ){
            JOptionPane.showMessageDialog(null,"UserName Already exists!");
            nameJTextField.setText("");
            passwordJTextField.setText("");
            return;
            }
        }
                UserAccount account = enterprise.getUserAccountDirectory().createUserAcount(username, password, new CustomerRole());
                JOptionPane.showMessageDialog(null, "Customer account created successfully!!!");
                break;
            }
        }
         
        nameJTextField.setText("");
        passwordJTextField.setText("");
        
        db4OUtil.storeSystem(system);
    }//GEN-LAST:event_CreateCustomerBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateCustomerBTN;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JTextField passwordJTextField;
    // End of variables declaration//GEN-END:variables
}
