/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Resturant;

import Business.AreYouHungrySystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Order.CustomerOrder;
import Business.Order.Order;
import Business.Organization.KitchenOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tczho
 */
public class KitchenJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private AreYouHungrySystem system;
    private DB4OUtil db4OUtil = DB4OUtil.getInstance();
    private KitchenOrganization kitchenOrganization;

    /**
     * Creates new form KitchenJPanel
     */
    public KitchenJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount, AreYouHungrySystem system,KitchenOrganization kitchenOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.system = system;
        this.kitchenOrganization=kitchenOrganization;
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) orderHistoryTBL.getModel();
        model.setRowCount(0);
       
        Network inNetwork = null;
        Enterprise inEnterprise = null;
        for(Network network : system.getNetworkList()){
            inNetwork = network;
        }
        for(Enterprise outEnterprise : inNetwork.getEnterpriseDirectory().getEnterpriseList()){
            if(outEnterprise.getEnterpriseType().toString().equals("Customer")){
                inEnterprise = outEnterprise;
            }
        }
        for(UserAccount outUserAccount : inEnterprise.getUserAccountDirectory().getUserAccountList()){
            for(Order order : outUserAccount.getOrderDirectory().getOrderList()){
                if(((CustomerOrder) order).getResturantName().equals(userAccount.getUsername())){
                    
                    Object[] row = new Object[6];

                    row[0] = order.getSender();
                    row[1] = order.getOrderStartDate();
                    row[2] = order.getOrderContent();
                    row[3] = ((CustomerOrder) order).getTotalPrice();
                    if(order.getStatus() == 1){
                        row[4] = "Waiting you for accepted this order";
                    }else if(order.getStatus() == 2){
                        row[4] = "You has taken this order, waiting for deliveryman";
                    }else if(order.getStatus() == 3){
                        row[4] = "This order has been delivered";
                    }else if(order.getStatus() == 4){
                        row[4] = "This order has been completed";
                    }else if(order.getStatus() == -2){
                        row[4] = "You have rejected this order";
                    }
                    row[5] = ((CustomerOrder) order);
                    model.addRow(row);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderHistoryTBL = new javax.swing.JTable();
        RejectOrderBTN = new javax.swing.JButton();
        MenuManagementBTN = new javax.swing.JButton();
        ConfirmBTN1 = new javax.swing.JButton();
        supplierCheckBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel181 = new javax.swing.JLabel();
        jLabel182 = new javax.swing.JLabel();
        jLabel183 = new javax.swing.JLabel();
        jLabel184 = new javax.swing.JLabel();
        jLabel185 = new javax.swing.JLabel();
        jLabel186 = new javax.swing.JLabel();
        jLabel187 = new javax.swing.JLabel();
        jLabel188 = new javax.swing.JLabel();
        jLabel189 = new javax.swing.JLabel();
        jLabel190 = new javax.swing.JLabel();
        jLabel191 = new javax.swing.JLabel();
        jLabel192 = new javax.swing.JLabel();
        jLabel193 = new javax.swing.JLabel();
        jLabel194 = new javax.swing.JLabel();
        jLabel195 = new javax.swing.JLabel();
        jLabel196 = new javax.swing.JLabel();
        jLabel197 = new javax.swing.JLabel();
        jLabel198 = new javax.swing.JLabel();
        jLabel199 = new javax.swing.JLabel();
        jLabel200 = new javax.swing.JLabel();
        jLabel201 = new javax.swing.JLabel();
        jLabel202 = new javax.swing.JLabel();
        jLabel203 = new javax.swing.JLabel();
        jLabel204 = new javax.swing.JLabel();
        jLabel205 = new javax.swing.JLabel();
        jLabel206 = new javax.swing.JLabel();
        jLabel207 = new javax.swing.JLabel();
        jLabel208 = new javax.swing.JLabel();
        jLabel209 = new javax.swing.JLabel();
        jLabel210 = new javax.swing.JLabel();
        jLabel211 = new javax.swing.JLabel();
        jLabel212 = new javax.swing.JLabel();
        jLabel213 = new javax.swing.JLabel();
        jLabel214 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel7.setText("Take-Away Service");

        setBackground(new java.awt.Color(255, 167, 62));
        setLayout(null);

        orderHistoryTBL.setBackground(new java.awt.Color(255, 102, 0));
        orderHistoryTBL.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        orderHistoryTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Order Date", "Dishes", "Total Price", "Order Status", "Resturant"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderHistoryTBL);

        add(jScrollPane1);
        jScrollPane1.setBounds(209, 222, 899, 184);

        RejectOrderBTN.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        RejectOrderBTN.setText("Reject Order");
        RejectOrderBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectOrderBTNActionPerformed(evt);
            }
        });
        add(RejectOrderBTN);
        RejectOrderBTN.setBounds(1148, 331, 190, 55);

        MenuManagementBTN.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        MenuManagementBTN.setText("Manage Resturant Menu");
        MenuManagementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuManagementBTNActionPerformed(evt);
            }
        });
        add(MenuManagementBTN);
        MenuManagementBTN.setBounds(209, 451, 315, 60);

        ConfirmBTN1.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        ConfirmBTN1.setText("Accept Order");
        ConfirmBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBTN1ActionPerformed(evt);
            }
        });
        add(ConfirmBTN1);
        ConfirmBTN1.setBounds(1148, 222, 190, 55);

        supplierCheckBTN.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        supplierCheckBTN.setText("Supplier Check");
        supplierCheckBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierCheckBTNActionPerformed(evt);
            }
        });
        add(supplierCheckBTN);
        supplierCheckBTN.setBounds(209, 544, 315, 60);

        jLabel1.setFont(new java.awt.Font("Silom", 0, 24)); // NOI18N
        jLabel1.setText("Resturant Order History");
        add(jLabel1);
        jLabel1.setBounds(541, 133, 325, 49);

        jLabel33.setFont(new java.awt.Font("Nanum Brush Script", 1, 80)); // NOI18N
        jLabel33.setText("Are You Hungry");
        add(jLabel33);
        jLabel33.setBounds(463, 0, 403, 93);

        jLabel5.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel5.setText("zzzzzzzzzzz");
        add(jLabel5);
        jLabel5.setBounds(209, 412, 176, 21);

        jLabel6.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel6.setText("zzzzzzzzzzz");
        add(jLabel6);
        jLabel6.setBounds(932, 195, 176, 21);

        jLabel8.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel8.setText("Take-Away Service");
        add(jLabel8);
        jLabel8.setBounds(878, 64, 155, 29);

        jButton1.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jButton1.setText("Request Supply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(209, 644, 315, 58);

        jLabel181.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel181.setText("h");
        add(jLabel181);
        jLabel181.setBounds(120, 160, 19, 20);

        jLabel182.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel182.setText("h");
        add(jLabel182);
        jLabel182.setBounds(340, 130, 19, 20);

        jLabel183.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel183.setText("h");
        add(jLabel183);
        jLabel183.setBounds(50, 40, 19, 20);

        jLabel184.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel184.setText("h");
        add(jLabel184);
        jLabel184.setBounds(660, 90, 19, 20);

        jLabel185.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel185.setText("h");
        add(jLabel185);
        jLabel185.setBounds(90, 710, 19, 20);

        jLabel186.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel186.setText("h");
        add(jLabel186);
        jLabel186.setBounds(250, 70, 19, 20);

        jLabel187.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel187.setText("h");
        add(jLabel187);
        jLabel187.setBounds(830, 470, 19, 20);

        jLabel188.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel188.setText("h");
        add(jLabel188);
        jLabel188.setBounds(130, 310, 19, 20);

        jLabel189.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel189.setText("h");
        add(jLabel189);
        jLabel189.setBounds(1070, 700, 19, 20);

        jLabel190.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel190.setText("h");
        add(jLabel190);
        jLabel190.setBounds(710, 680, 19, 20);

        jLabel191.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel191.setText("h");
        add(jLabel191);
        jLabel191.setBounds(930, 530, 19, 20);

        jLabel192.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel192.setText("h");
        add(jLabel192);
        jLabel192.setBounds(660, 500, 19, 20);

        jLabel193.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel193.setText("h");
        add(jLabel193);
        jLabel193.setBounds(1230, 590, 19, 20);

        jLabel194.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel194.setText("h");
        add(jLabel194);
        jLabel194.setBounds(1230, 460, 19, 20);

        jLabel195.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel195.setText("h");
        add(jLabel195);
        jLabel195.setBounds(1510, 580, 19, 20);

        jLabel196.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel196.setText("h");
        add(jLabel196);
        jLabel196.setBounds(1080, 500, 19, 20);

        jLabel197.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel197.setText("h");
        add(jLabel197);
        jLabel197.setBounds(1370, 280, 19, 20);

        jLabel198.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel198.setText("h");
        add(jLabel198);
        jLabel198.setBounds(1080, 630, 19, 20);

        jLabel199.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel199.setText("h");
        add(jLabel199);
        jLabel199.setBounds(1140, 130, 19, 20);

        jLabel200.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel200.setText("h");
        add(jLabel200);
        jLabel200.setBounds(1520, 420, 19, 20);

        jLabel201.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel201.setText("h");
        add(jLabel201);
        jLabel201.setBounds(1250, 30, 19, 20);

        jLabel202.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel202.setText("h");
        add(jLabel202);
        jLabel202.setBounds(1470, 80, 19, 20);

        jLabel203.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel203.setText("h");
        add(jLabel203);
        jLabel203.setBounds(320, 750, 19, 20);

        jLabel204.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel204.setText("h");
        add(jLabel204);
        jLabel204.setBounds(40, 470, 19, 20);

        jLabel205.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel205.setText("h");
        add(jLabel205);
        jLabel205.setBounds(140, 560, 19, 20);

        jLabel206.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel206.setText("h");
        add(jLabel206);
        jLabel206.setBounds(600, 740, 19, 20);

        jLabel207.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel207.setText("h");
        add(jLabel207);
        jLabel207.setBounds(860, 620, 19, 20);

        jLabel208.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel208.setText("h");
        add(jLabel208);
        jLabel208.setBounds(1530, 250, 19, 20);

        jLabel209.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel209.setText("h");
        add(jLabel209);
        jLabel209.setBounds(1370, 490, 19, 20);

        jLabel210.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel210.setText("h");
        add(jLabel210);
        jLabel210.setBounds(1510, 710, 19, 20);

        jLabel211.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel211.setText("h");
        add(jLabel211);
        jLabel211.setBounds(1340, 680, 19, 20);

        jLabel212.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel212.setText("h");
        add(jLabel212);
        jLabel212.setBounds(1310, 140, 19, 20);

        jLabel213.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel213.setText("h");
        add(jLabel213);
        jLabel213.setBounds(940, 130, 19, 20);

        jLabel214.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel214.setText("h");
        add(jLabel214);
        jLabel214.setBounds(450, 90, 19, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuManagementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuManagementBTNActionPerformed
        MenuManagementJPanel panel = new MenuManagementJPanel(userProcessContainer, userAccount, system);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("MenuManagementJPanel", panel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_MenuManagementBTNActionPerformed

    private void RejectOrderBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectOrderBTNActionPerformed
        int selectedRow = orderHistoryTBL.getSelectedRow();
        if(selectedRow>=0){
            Order order = (Order)orderHistoryTBL.getValueAt(selectedRow, 5);
            if(order.getStatus() ==1){
                int selectionButton = JOptionPane.YES_NO_OPTION;
                int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to reject this order???","Warning",selectionButton);
                if(selectionResult == JOptionPane.YES_OPTION){
                    order.setStatus(-2);
                    populateTable();
                    db4OUtil.storeSystem(system);
                    JOptionPane.showMessageDialog(null, "You have rejected this order!!!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "You cannot Reject this Order!!!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_RejectOrderBTNActionPerformed

    private void ConfirmBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBTN1ActionPerformed
        int selectedRow = orderHistoryTBL.getSelectedRow();
        if(selectedRow>=0){
            Order order = (Order)orderHistoryTBL.getValueAt(selectedRow, 5);
            if(order.getStatus() ==1){
                int selectionButton = JOptionPane.YES_NO_OPTION;
                int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to accept this order???","Warning",selectionButton);
                if(selectionResult == JOptionPane.YES_OPTION){
                    order.setStatus(2);
                    populateTable();
                    db4OUtil.storeSystem(system);
                    JOptionPane.showMessageDialog(null, "You have successfully accept this order!!!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "You cannot accept this Order!!!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_ConfirmBTN1ActionPerformed

    private void supplierCheckBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierCheckBTNActionPerformed
        ResturantSupplierCheckJPanel panel = new ResturantSupplierCheckJPanel(userProcessContainer, userAccount, system);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("MenuManagementJPanel", panel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_supplierCheckBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RequestSupplyJPanel panel = new RequestSupplyJPanel(userProcessContainer, userAccount, kitchenOrganization,system, enterprise);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("RequestSupplyJPanel", panel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmBTN1;
    private javax.swing.JButton MenuManagementBTN;
    private javax.swing.JButton RejectOrderBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel190;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel192;
    private javax.swing.JLabel jLabel193;
    private javax.swing.JLabel jLabel194;
    private javax.swing.JLabel jLabel195;
    private javax.swing.JLabel jLabel196;
    private javax.swing.JLabel jLabel197;
    private javax.swing.JLabel jLabel198;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderHistoryTBL;
    private javax.swing.JButton supplierCheckBTN;
    // End of variables declaration//GEN-END:variables
}
