/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Resturant;

import Business.AreYouHungrySystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Order.MenuOrder;
import Business.Order.Order;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author tczho
 */
public class MenuManagementJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private AreYouHungrySystem system;
    private DB4OUtil db4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form MenuManagementJPanel
     */
    MenuManagementJPanel(JPanel userProcessContainer, UserAccount userAccount, AreYouHungrySystem system) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        
        populateDate();
       
    }

       
    public void populateDate(){
        if(userAccount.getOrderDirectory().getOrderList().size() != 0){
            for(Order order : userAccount.getOrderDirectory().getOrderList()){
                dish1JTextField.setText(((MenuOrder) order).getDish1());
                dish2JTextField.setText(((MenuOrder) order).getDish2());
                dish3JTextField.setText(((MenuOrder) order).getDish3());
                dish4JTextField.setText(((MenuOrder) order).getDish4());
                dish5JTextField.setText(((MenuOrder) order).getDish5());
                dish6JTextField.setText(((MenuOrder) order).getDish6());
                dish7JTextField.setText(((MenuOrder) order).getDish7());
                dish8JTextField.setText(((MenuOrder) order).getDish8());
                
                price1JTextField.setText(String.valueOf(((MenuOrder) order).getPrice1()));
                price2JTextField.setText(String.valueOf(((MenuOrder) order).getPrice2()));
                price3JTextField.setText(String.valueOf(((MenuOrder) order).getPrice3()));
                price4JTextField.setText(String.valueOf(((MenuOrder) order).getPrice4()));
                price5JTextField.setText(String.valueOf(((MenuOrder) order).getPrice5()));
                price6JTextField.setText(String.valueOf(((MenuOrder) order).getPrice6()));
                price7JTextField.setText(String.valueOf(((MenuOrder) order).getPrice7()));
                price8JTextField.setText(String.valueOf(((MenuOrder) order).getPrice8()));
                
                jLabel11.setIcon((Icon) ((MenuOrder) order).getDish11());
                jLabel12.setIcon((Icon) ((MenuOrder) order).getDish12());
                jLabel13.setIcon((Icon) ((MenuOrder) order).getDish13());
                jLabel14.setIcon((Icon) ((MenuOrder) order).getDish14());
                jLabel15.setIcon((Icon) ((MenuOrder) order).getDish15());
                jLabel16.setIcon((Icon) ((MenuOrder) order).getDish16());
                jLabel17.setIcon((Icon) ((MenuOrder) order).getDish17());
                jLabel18.setIcon((Icon) ((MenuOrder) order).getDish18());
            }
        }else{
            dish1JTextField.setText("Not set");
            dish2JTextField.setText("Not set");
            dish3JTextField.setText("Not set");
            dish4JTextField.setText("Not set");
            dish5JTextField.setText("Not set");
            dish6JTextField.setText("Not set");
            dish7JTextField.setText("Not set");
            dish8JTextField.setText("Not set");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        dish1JTextField = new javax.swing.JTextField();
        dish2JTextField = new javax.swing.JTextField();
        dish3JTextField = new javax.swing.JTextField();
        dish4JTextField = new javax.swing.JTextField();
        dish5JTextField = new javax.swing.JTextField();
        dish6JTextField = new javax.swing.JTextField();
        dish7JTextField = new javax.swing.JTextField();
        dish8JTextField = new javax.swing.JTextField();
        ConfirmBTN = new javax.swing.JButton();
        UpdateBTN = new javax.swing.JButton();
        backjButton2 = new javax.swing.JButton();
        price1JTextField = new javax.swing.JTextField();
        price2JTextField = new javax.swing.JTextField();
        price4JTextField = new javax.swing.JTextField();
        price5JTextField = new javax.swing.JTextField();
        price3JTextField = new javax.swing.JTextField();
        price6JTextField = new javax.swing.JTextField();
        price7JTextField = new javax.swing.JTextField();
        price8JTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnDish7 = new javax.swing.JButton();
        btnDish1 = new javax.swing.JButton();
        btnDish3 = new javax.swing.JButton();
        btnDish2 = new javax.swing.JButton();
        btnDish5 = new javax.swing.JButton();
        btnDish4 = new javax.swing.JButton();
        btnDish6 = new javax.swing.JButton();
        btnDish8 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel182 = new javax.swing.JLabel();
        jLabel183 = new javax.swing.JLabel();
        jLabel184 = new javax.swing.JLabel();
        jLabel185 = new javax.swing.JLabel();
        jLabel186 = new javax.swing.JLabel();
        jLabel187 = new javax.swing.JLabel();
        jLabel188 = new javax.swing.JLabel();
        jLabel189 = new javax.swing.JLabel();
        jLabel190 = new javax.swing.JLabel();
        jLabel191 = new javax.swing.JLabel();
        jLabel192 = new javax.swing.JLabel();
        jLabel193 = new javax.swing.JLabel();
        jLabel194 = new javax.swing.JLabel();
        jLabel195 = new javax.swing.JLabel();
        jLabel196 = new javax.swing.JLabel();
        jLabel197 = new javax.swing.JLabel();
        jLabel198 = new javax.swing.JLabel();
        jLabel199 = new javax.swing.JLabel();
        jLabel200 = new javax.swing.JLabel();
        jLabel201 = new javax.swing.JLabel();
        jLabel202 = new javax.swing.JLabel();
        jLabel203 = new javax.swing.JLabel();
        jLabel204 = new javax.swing.JLabel();
        jLabel205 = new javax.swing.JLabel();
        jLabel206 = new javax.swing.JLabel();
        jLabel207 = new javax.swing.JLabel();
        jLabel208 = new javax.swing.JLabel();
        jLabel209 = new javax.swing.JLabel();
        jLabel210 = new javax.swing.JLabel();
        jLabel211 = new javax.swing.JLabel();
        jLabel212 = new javax.swing.JLabel();
        jLabel213 = new javax.swing.JLabel();
        jLabel214 = new javax.swing.JLabel();
        jLabel215 = new javax.swing.JLabel();
        jLabel216 = new javax.swing.JLabel();
        jLabel217 = new javax.swing.JLabel();

        jLabel34.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel34.setText("NO.7");

        jLabel36.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel36.setText("NO.8");

        setBackground(new java.awt.Color(255, 167, 62));
        setLayout(null);

        dish1JTextField.setEditable(false);
        dish1JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(dish1JTextField);
        dish1JTextField.setBounds(584, 171, 164, 28);

        dish2JTextField.setEditable(false);
        dish2JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(dish2JTextField);
        dish2JTextField.setBounds(584, 234, 164, 28);

        dish3JTextField.setEditable(false);
        dish3JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(dish3JTextField);
        dish3JTextField.setBounds(584, 296, 164, 28);

        dish4JTextField.setEditable(false);
        dish4JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(dish4JTextField);
        dish4JTextField.setBounds(584, 353, 164, 28);

        dish5JTextField.setEditable(false);
        dish5JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dish5JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish5JTextFieldActionPerformed(evt);
            }
        });
        add(dish5JTextField);
        dish5JTextField.setBounds(584, 415, 164, 28);

        dish6JTextField.setEditable(false);
        dish6JTextField.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        dish6JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish6JTextFieldActionPerformed(evt);
            }
        });
        add(dish6JTextField);
        dish6JTextField.setBounds(584, 473, 164, 29);

        dish7JTextField.setEditable(false);
        dish7JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dish7JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish7JTextFieldActionPerformed(evt);
            }
        });
        add(dish7JTextField);
        dish7JTextField.setBounds(584, 533, 164, 28);

        dish8JTextField.setEditable(false);
        dish8JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dish8JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish8JTextFieldActionPerformed(evt);
            }
        });
        add(dish8JTextField);
        dish8JTextField.setBounds(584, 604, 164, 28);

        ConfirmBTN.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        ConfirmBTN.setText("Confirm Dishes");
        ConfirmBTN.setEnabled(false);
        ConfirmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBTNActionPerformed(evt);
            }
        });
        add(ConfirmBTN);
        ConfirmBTN.setBounds(650, 670, 189, 50);

        UpdateBTN.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        UpdateBTN.setText("Update Dishes");
        UpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTNActionPerformed(evt);
            }
        });
        add(UpdateBTN);
        UpdateBTN.setBounds(910, 670, 180, 50);

        backjButton2.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        backjButton2.setText("<< Back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });
        add(backjButton2);
        backjButton2.setBounds(1433, 48, 114, 45);

        price1JTextField.setEditable(false);
        price1JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price1JTextField);
        price1JTextField.setBounds(900, 171, 80, 28);

        price2JTextField.setEditable(false);
        price2JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price2JTextField);
        price2JTextField.setBounds(900, 231, 80, 28);

        price4JTextField.setEditable(false);
        price4JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price4JTextField);
        price4JTextField.setBounds(900, 353, 80, 28);

        price5JTextField.setEditable(false);
        price5JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price5JTextField);
        price5JTextField.setBounds(900, 415, 80, 28);

        price3JTextField.setEditable(false);
        price3JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price3JTextField);
        price3JTextField.setBounds(900, 296, 80, 28);

        price6JTextField.setEditable(false);
        price6JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price6JTextField);
        price6JTextField.setBounds(900, 472, 80, 28);

        price7JTextField.setEditable(false);
        price7JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price7JTextField);
        price7JTextField.setBounds(900, 533, 80, 28);

        price8JTextField.setEditable(false);
        price8JTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(price8JTextField);
        price8JTextField.setBounds(900, 604, 80, 28);
        add(jLabel11);
        jLabel11.setBounds(1280, 168, 116, 98);
        add(jLabel12);
        jLabel12.setBounds(1280, 291, 116, 98);
        add(jLabel14);
        jLabel14.setBounds(1280, 537, 116, 98);
        add(jLabel16);
        jLabel16.setBounds(1481, 291, 116, 98);
        add(jLabel17);
        jLabel17.setBounds(1483, 414, 116, 98);
        add(jLabel13);
        jLabel13.setBounds(1280, 414, 116, 98);
        add(jLabel15);
        jLabel15.setBounds(1481, 168, 116, 98);
        add(jLabel18);
        jLabel18.setBounds(1483, 537, 116, 98);

        btnDish7.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        btnDish7.setText("Upload");
        btnDish7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDish7ActionPerformed(evt);
            }
        });
        add(btnDish7);
        btnDish7.setBounds(1047, 535, 94, 28);

        btnDish1.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        btnDish1.setText("Upload");
        btnDish1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDish1ActionPerformed(evt);
            }
        });
        add(btnDish1);
        btnDish1.setBounds(1047, 173, 94, 28);

        btnDish3.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        btnDish3.setText("Upload");
        btnDish3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDish3ActionPerformed(evt);
            }
        });
        add(btnDish3);
        btnDish3.setBounds(1047, 298, 94, 28);

        btnDish2.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        btnDish2.setText("Upload");
        btnDish2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDish2ActionPerformed(evt);
            }
        });
        add(btnDish2);
        btnDish2.setBounds(1047, 236, 94, 28);

        btnDish5.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        btnDish5.setText("Upload");
        btnDish5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDish5ActionPerformed(evt);
            }
        });
        add(btnDish5);
        btnDish5.setBounds(1047, 417, 94, 28);

        btnDish4.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        btnDish4.setText("Upload");
        btnDish4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDish4ActionPerformed(evt);
            }
        });
        add(btnDish4);
        btnDish4.setBounds(1047, 355, 94, 28);

        btnDish6.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        btnDish6.setText("Upload");
        btnDish6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDish6ActionPerformed(evt);
            }
        });
        add(btnDish6);
        btnDish6.setBounds(1047, 474, 94, 28);

        btnDish8.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        btnDish8.setText("Upload");
        btnDish8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDish8ActionPerformed(evt);
            }
        });
        add(btnDish8);
        btnDish8.setBounds(1047, 606, 94, 28);

        jLabel33.setFont(new java.awt.Font("Nanum Brush Script", 1, 80)); // NOI18N
        jLabel33.setText("Are You Hungry");
        add(jLabel33);
        jLabel33.setBounds(782, 0, 403, 93);

        jLabel19.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel19.setText("NO.1");
        add(jLabel19);
        jLabel19.setBounds(526, 172, 33, 29);

        jLabel9.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel9.setText("NO.2");
        add(jLabel9);
        jLabel9.setBounds(526, 231, 36, 29);

        jLabel28.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel28.setText("NO.3");
        add(jLabel28);
        jLabel28.setBounds(526, 293, 36, 29);

        jLabel30.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel30.setText("NO.4");
        add(jLabel30);
        jLabel30.setBounds(526, 350, 40, 29);

        jLabel31.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel31.setText("NO.5");
        add(jLabel31);
        jLabel31.setBounds(1433, 168, 36, 29);

        jLabel32.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel32.setText("NO.6");
        add(jLabel32);
        jLabel32.setBounds(1433, 291, 36, 29);

        jLabel35.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel35.setText("NO.7");
        add(jLabel35);
        jLabel35.setBounds(1433, 414, 38, 29);

        jLabel37.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel37.setText("NO.8");
        add(jLabel37);
        jLabel37.setBounds(531, 601, 35, 29);

        jLabel38.setFont(new java.awt.Font("Nanum Brush Script", 0, 36)); // NOI18N
        jLabel38.setText("Menu");
        add(jLabel38);
        jLabel38.setBounds(619, 132, 75, 28);

        jLabel6.setFont(new java.awt.Font("Nanum Brush Script", 0, 36)); // NOI18N
        jLabel6.setText("Price");
        add(jLabel6);
        jLabel6.setBounds(900, 125, 60, 43);

        jLabel39.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel39.setText("NO.1");
        add(jLabel39);
        jLabel39.setBounds(1228, 168, 33, 29);

        jLabel10.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel10.setText("NO.2");
        add(jLabel10);
        jLabel10.setBounds(1228, 283, 36, 29);

        jLabel40.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel40.setText("NO.3");
        add(jLabel40);
        jLabel40.setBounds(1228, 412, 36, 29);

        jLabel41.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel41.setText("NO.4");
        add(jLabel41);
        jLabel41.setBounds(1228, 542, 40, 29);

        jLabel42.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel42.setText("NO.5");
        add(jLabel42);
        jLabel42.setBounds(526, 416, 36, 29);

        jLabel43.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel43.setText("NO.6");
        add(jLabel43);
        jLabel43.setBounds(530, 473, 36, 29);

        jLabel44.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel44.setText("NO.7");
        add(jLabel44);
        jLabel44.setBounds(528, 534, 38, 29);

        jLabel45.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel45.setText("NO.8");
        add(jLabel45);
        jLabel45.setBounds(1436, 537, 35, 29);

        jLabel7.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel7.setText("Take-Away Service");
        add(jLabel7);
        jLabel7.setBounds(1197, 64, 155, 29);

        jLabel182.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel182.setText("h");
        add(jLabel182);
        jLabel182.setBounds(860, 260, 19, 20);

        jLabel183.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel183.setText("h");
        add(jLabel183);
        jLabel183.setBounds(270, 70, 19, 20);

        jLabel184.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel184.setText("h");
        add(jLabel184);
        jLabel184.setBounds(380, 390, 19, 20);

        jLabel185.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel185.setText("h");
        add(jLabel185);
        jLabel185.setBounds(380, 250, 19, 20);

        jLabel186.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel186.setText("h");
        add(jLabel186);
        jLabel186.setBounds(360, 140, 19, 20);

        jLabel187.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel187.setText("h");
        add(jLabel187);
        jLabel187.setBounds(110, 160, 19, 20);

        jLabel188.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel188.setText("h");
        add(jLabel188);
        jLabel188.setBounds(220, 230, 19, 20);

        jLabel189.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel189.setText("h");
        add(jLabel189);
        jLabel189.setBounds(140, 450, 19, 20);

        jLabel190.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel190.setText("h");
        add(jLabel190);
        jLabel190.setBounds(160, 630, 19, 20);

        jLabel191.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel191.setText("h");
        add(jLabel191);
        jLabel191.setBounds(220, 350, 19, 20);

        jLabel192.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel192.setText("h");
        add(jLabel192);
        jLabel192.setBounds(160, 720, 19, 20);

        jLabel193.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel193.setText("h");
        add(jLabel193);
        jLabel193.setBounds(640, 770, 19, 20);

        jLabel194.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel194.setText("h");
        add(jLabel194);
        jLabel194.setBounds(340, 520, 19, 20);

        jLabel195.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel195.setText("h");
        add(jLabel195);
        jLabel195.setBounds(350, 790, 19, 20);

        jLabel196.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel196.setText("h");
        add(jLabel196);
        jLabel196.setBounds(300, 660, 19, 20);

        jLabel197.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel197.setText("h");
        add(jLabel197);
        jLabel197.setBounds(1220, 730, 19, 20);

        jLabel198.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel198.setText("h");
        add(jLabel198);
        jLabel198.setBounds(510, 680, 19, 20);

        jLabel199.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel199.setText("h");
        add(jLabel199);
        jLabel199.setBounds(1580, 590, 19, 20);

        jLabel200.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel200.setText("h");
        add(jLabel200);
        jLabel200.setBounds(900, 770, 19, 20);

        jLabel201.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel201.setText("h");
        add(jLabel201);
        jLabel201.setBounds(1630, 50, 19, 20);

        jLabel202.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel202.setText("h");
        add(jLabel202);
        jLabel202.setBounds(1440, 710, 19, 20);

        jLabel203.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel203.setText("h");
        add(jLabel203);
        jLabel203.setBounds(1330, 480, 19, 20);

        jLabel204.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel204.setText("h");
        add(jLabel204);
        jLabel204.setBounds(1610, 760, 19, 20);

        jLabel205.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel205.setText("h");
        add(jLabel205);
        jLabel205.setBounds(1300, 250, 19, 20);

        jLabel206.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel206.setText("h");
        add(jLabel206);
        jLabel206.setBounds(1640, 470, 19, 20);

        jLabel207.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel207.setText("h");
        add(jLabel207);
        jLabel207.setBounds(1380, 120, 19, 20);

        jLabel208.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel208.setText("h");
        add(jLabel208);
        jLabel208.setBounds(1550, 200, 19, 20);

        jLabel209.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel209.setText("h");
        add(jLabel209);
        jLabel209.setBounds(640, 50, 19, 20);

        jLabel210.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel210.setText("h");
        add(jLabel210);
        jLabel210.setBounds(520, 70, 19, 20);

        jLabel211.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel211.setText("h");
        add(jLabel211);
        jLabel211.setBounds(1000, 490, 19, 20);

        jLabel212.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel212.setText("h");
        add(jLabel212);
        jLabel212.setBounds(800, 110, 19, 20);

        jLabel213.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel213.setText("h");
        add(jLabel213);
        jLabel213.setBounds(780, 390, 19, 20);

        jLabel214.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel214.setText("h");
        add(jLabel214);
        jLabel214.setBounds(1020, 400, 19, 20);

        jLabel215.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel215.setText("h");
        add(jLabel215);
        jLabel215.setBounds(850, 550, 19, 20);

        jLabel216.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel216.setText("h");
        add(jLabel216);
        jLabel216.setBounds(1540, 390, 19, 20);

        jLabel217.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel217.setText("h");
        add(jLabel217);
        jLabel217.setBounds(1630, 260, 19, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void dish5JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish5JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dish5JTextFieldActionPerformed

    private void dish6JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish6JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dish6JTextFieldActionPerformed

    private void dish7JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish7JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dish7JTextFieldActionPerformed

    private void dish8JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish8JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dish8JTextFieldActionPerformed

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton2ActionPerformed

    private void UpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTNActionPerformed
        dish1JTextField.setEditable(true);
        dish2JTextField.setEditable(true);
        dish3JTextField.setEditable(true);
        dish4JTextField.setEditable(true);
        dish5JTextField.setEditable(true);
        dish6JTextField.setEditable(true);
        dish7JTextField.setEditable(true);
        dish8JTextField.setEditable(true);
        
        price1JTextField.setEditable(true);
        price2JTextField.setEditable(true);
        price3JTextField.setEditable(true);
        price4JTextField.setEditable(true);
        price5JTextField.setEditable(true);
        price6JTextField.setEditable(true);
        price7JTextField.setEditable(true);
        price8JTextField.setEditable(true);
        
        ConfirmBTN.setEnabled(true);
        UpdateBTN.setEnabled(false);
    }//GEN-LAST:event_UpdateBTNActionPerformed

    private void ConfirmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBTNActionPerformed
        
        
        String dish1=dish1JTextField.getText();
        if(!dish1.equals("")&&!price1JTextField.getText().equals(""))
        {
        dish1 = dish1JTextField.getText();
        }
        if(dish1.equals("Not set")||price1JTextField.getText().equals("")||price1JTextField.getText().equals("0.0")||price1JTextField.getText().equals("0"))
        {
        dish1="";
        }
       
        
        String dish2 = dish2JTextField.getText();
        if(!dish2.equals("")&&!price2JTextField.getText().equals(""))
        {
        dish2 = dish2JTextField.getText();
        }
        if(dish2.equals("Not set")||price2JTextField.getText().equals("")||price2JTextField.getText().equals("0.0")||price2JTextField.getText().equals("0"))
        {
        dish2="";
        }
        
        
        String dish3 = dish3JTextField.getText();
        if(!dish3.equals("")&&!price3JTextField.getText().equals(""))
        {
        dish3 = dish3JTextField.getText();
        }
        if(dish3.equals("Not set")||price3JTextField.getText().equals("")||price3JTextField.getText().equals("0.0")||price3JTextField.getText().equals("0"))
        {
        dish3="";
        }
        
        
        String dish4 = dish4JTextField.getText();
        if(!dish4.equals("")&&!price4JTextField.getText().equals(""))
        {
        dish4 = dish4JTextField.getText();
        }
        if(dish4.equals("Not set")||price4JTextField.getText().equals("")||price4JTextField.getText().equals("0.0")||price4JTextField.getText().equals("0"))
        {
        dish4="";
        }
        
        
        String dish5 = dish5JTextField.getText();
        if(!dish5.equals("")&&!price5JTextField.getText().equals(""))
        {
        dish5 = dish5JTextField.getText();
        }

        if(dish5.equals("Not set")||price5JTextField.getText().equals("")||price5JTextField.getText().equals("0.0")||price5JTextField.getText().equals("0"))
        {
        dish5="";
        }
        
        
        String dish6 = dish6JTextField.getText();
        if(!dish6.equals("")&&!price6JTextField.getText().equals(""))
        {
        dish6 = dish6JTextField.getText();
        }
        if(dish6.equals("Not set")||price6JTextField.getText().equals("")||price6JTextField.getText().equals("0.0")||price6JTextField.getText().equals("0"))
        {
        dish6="";
        }
        
        
        String dish7 = dish7JTextField.getText();
        if(!dish7.equals("")&&!price7JTextField.getText().equals(""))
        {
        dish7 = dish7JTextField.getText();
        }
        if(dish7.equals("Not set")||price7JTextField.getText().equals("")||price7JTextField.getText().equals("0.0")||price7JTextField.getText().equals("0"))
        {
        dish7="";
        }
        
        
        String dish8 = dish8JTextField.getText();
        if(!dish8.equals("")&&!price8JTextField.getText().equals(""))
        {
        dish8 = dish8JTextField.getText();
        }
        if(dish8.equals("Not set")||price8JTextField.getText().equals("")||price8JTextField.getText().equals("0.0")||price8JTextField.getText().equals("0"))
        {
        dish8="";
        }
        
        Double price1=0.0;
        Double price2=0.0;
        Double price3=0.0;
        Double price4=0.0;
        Double price5=0.0;
        Double price6=0.0;
        Double price7=0.0;
        Double price8=0.0;
        

        if(!dish1.equals("")&&!price1JTextField.getText().equals("")&&!price1JTextField.getText().equals("0.0")&&!price1JTextField.getText().equals("0"))
        {
        price1 = Double.parseDouble(price1JTextField.getText());
        }

        if(!dish2.equals("")&&!price2JTextField.getText().equals("")&&!price2JTextField.getText().equals("0.0")&&!price2JTextField.getText().equals("0"))
         {
        price2 = Double.parseDouble(price2JTextField.getText());
         }
         
        if(!dish3.equals("")&&!price3JTextField.getText().equals("")&&!price3JTextField.getText().equals("0.0")&&!price3JTextField.getText().equals("0"))
        {
        price3 = Double.parseDouble(price3JTextField.getText());
        }
        
        if(!dish4.equals("")&&!price4JTextField.getText().equals("")&&!price4JTextField.getText().equals("0.0")&&!price4JTextField.getText().equals("0"))
        {
        price4 = Double.parseDouble(price4JTextField.getText());
        } 
        
        if(!dish5.equals("")&&!price5JTextField.getText().equals("")&&!price5JTextField.getText().equals("0.0")&&!price5JTextField.getText().equals("0"))
        {
        price5 = Double.parseDouble(price5JTextField.getText());
        } 
        
        if(!dish6.equals("")&&!price6JTextField.getText().equals("")&&!price6JTextField.getText().equals("0.0")&&!price6JTextField.getText().equals("0"))
        {
        price6 = Double.parseDouble(price6JTextField.getText());
        } 
        
        if(!dish7.equals("")&&!price7JTextField.getText().equals("")&&!price7JTextField.getText().equals("0.0")&&!price7JTextField.getText().equals("0"))
        {
        price7 = Double.parseDouble(price7JTextField.getText());
        } 
        
        if(!dish8.equals("")&&!price8JTextField.getText().equals("")&&!price8JTextField.getText().equals("0.0")&&!price8JTextField.getText().equals("0"))
        {
        price8 = Double.parseDouble(price8JTextField.getText());
        }
        
        
        ImageIcon dish11=(ImageIcon) jLabel11.getIcon();
        ImageIcon dish12=(ImageIcon) jLabel12.getIcon();
        ImageIcon dish13=(ImageIcon) jLabel13.getIcon();
        ImageIcon dish14=(ImageIcon) jLabel14.getIcon();
        ImageIcon dish15=(ImageIcon) jLabel15.getIcon();
        ImageIcon dish16=(ImageIcon) jLabel16.getIcon();
        ImageIcon dish17=(ImageIcon) jLabel17.getIcon();
        ImageIcon dish18=(ImageIcon) jLabel18.getIcon();
        
        MenuOrder order = new MenuOrder();
        
        
        order.setDish1(dish1);
        order.setDish2(dish2);
        order.setDish3(dish3);
        order.setDish4(dish4);
        order.setDish5(dish5);
        order.setDish6(dish6);
        order.setDish7(dish7);
        order.setDish8(dish8);
        
        order.setPrice1(price1);
        order.setPrice2(price2);
        order.setPrice3(price3);
        order.setPrice4(price4);
        order.setPrice5(price5);
        order.setPrice6(price6);
        order.setPrice7(price7);
        order.setPrice8(price8);
        
        order.setDish11(dish11);
        order.setDish12(dish12);
        order.setDish13(dish13);
        order.setDish14(dish14);
        order.setDish15(dish15);
        order.setDish16(dish16);
        order.setDish17(dish17);
        order.setDish18(dish18);
        
        
        if(userAccount.getOrderDirectory().getOrderList().size() == 0){
            userAccount.getOrderDirectory().getOrderList().add(order);
        }else{
            for(Order menuOrder : userAccount.getOrderDirectory().getOrderList()){
                ((MenuOrder) menuOrder).setDish1(dish1);
                ((MenuOrder) menuOrder).setDish2(dish2);
                ((MenuOrder) menuOrder).setDish3(dish3);
                ((MenuOrder) menuOrder).setDish4(dish4);
                ((MenuOrder) menuOrder).setDish5(dish5);
                ((MenuOrder) menuOrder).setDish6(dish6);
                ((MenuOrder) menuOrder).setDish7(dish7);
                ((MenuOrder) menuOrder).setDish8(dish8);
                
                ((MenuOrder) menuOrder).setPrice1(price1);
                ((MenuOrder) menuOrder).setPrice2(price2);
                ((MenuOrder) menuOrder).setPrice3(price3);
                ((MenuOrder) menuOrder).setPrice4(price4);
                ((MenuOrder) menuOrder).setPrice5(price5);
                ((MenuOrder) menuOrder).setPrice6(price6);
                ((MenuOrder) menuOrder).setPrice7(price7);
                ((MenuOrder) menuOrder).setPrice8(price8);
                
                ((MenuOrder) menuOrder).setDish11(dish11);
                ((MenuOrder) menuOrder).setDish12(dish12);
                ((MenuOrder) menuOrder).setDish13(dish13);
                ((MenuOrder) menuOrder).setDish14(dish14);
                ((MenuOrder) menuOrder).setDish15(dish15);
                ((MenuOrder) menuOrder).setDish16(dish16);
                ((MenuOrder) menuOrder).setDish17(dish17);
                ((MenuOrder) menuOrder).setDish18(dish18);
            }
        }
        if(userAccount.getOrderDirectory().orderList.size() == 0){
            userAccount.getOrderDirectory().orderList.add(order);
        }else{
            for(Order menuOrder : userAccount.getOrderDirectory().getOrderList()){
                ((MenuOrder) menuOrder).setDish1(dish1);
                ((MenuOrder) menuOrder).setDish2(dish2);
                ((MenuOrder) menuOrder).setDish3(dish3);
                ((MenuOrder) menuOrder).setDish4(dish4);
                ((MenuOrder) menuOrder).setDish5(dish5);
                ((MenuOrder) menuOrder).setDish6(dish6);
                ((MenuOrder) menuOrder).setDish7(dish7);
                ((MenuOrder) menuOrder).setDish8(dish8);
                
                ((MenuOrder) menuOrder).setPrice1(price1);
                ((MenuOrder) menuOrder).setPrice2(price2);
                ((MenuOrder) menuOrder).setPrice3(price3);
                ((MenuOrder) menuOrder).setPrice4(price4);
                ((MenuOrder) menuOrder).setPrice5(price5);
                ((MenuOrder) menuOrder).setPrice6(price6);
                ((MenuOrder) menuOrder).setPrice7(price7);
                ((MenuOrder) menuOrder).setPrice8(price8);
                
                ((MenuOrder) menuOrder).setDish11(dish11);
                ((MenuOrder) menuOrder).setDish12(dish12);
                ((MenuOrder) menuOrder).setDish13(dish13);
                ((MenuOrder) menuOrder).setDish14(dish14);
                ((MenuOrder) menuOrder).setDish15(dish15);
                ((MenuOrder) menuOrder).setDish16(dish16);
                ((MenuOrder) menuOrder).setDish17(dish17);
                ((MenuOrder) menuOrder).setDish18(dish18);
            }
        }
        db4OUtil.storeSystem(system);
        
        dish1JTextField.setEditable(false);
        dish2JTextField.setEditable(false);
        dish3JTextField.setEditable(false);
        dish4JTextField.setEditable(false);
        dish5JTextField.setEditable(false);
        dish6JTextField.setEditable(false);
        dish7JTextField.setEditable(false);
        dish8JTextField.setEditable(false);
        
        price1JTextField.setEditable(false);
        price2JTextField.setEditable(false);
        price3JTextField.setEditable(false);
        price4JTextField.setEditable(false);
        price5JTextField.setEditable(false);
        price6JTextField.setEditable(false);
        price7JTextField.setEditable(false);
        price8JTextField.setEditable(false);
        
        ConfirmBTN.setEnabled(false);
        UpdateBTN.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Dishes Updated!");

        populateDate();
    }//GEN-LAST:event_ConfirmBTNActionPerformed

    private void btnDish7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDish7ActionPerformed
        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter ("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int photo=file.showSaveDialog(null);

        if(photo==JFileChooser.APPROVE_OPTION)
        {
            File selectedFile=file.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            jLabel17.setIcon(ResizeImage(path));
            JOptionPane.showMessageDialog(null,"Upload Dish Image Successfully");

        }
        else if(photo==JFileChooser.CANCEL_OPTION)
        {
            JOptionPane.showMessageDialog(null,"Failed");
        }
        jLabel17.setSize(120,100);
        setVisible(true);
    }//GEN-LAST:event_btnDish7ActionPerformed

    private void btnDish1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDish1ActionPerformed
        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter ("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int photo=file.showSaveDialog(null);

        if(photo==JFileChooser.APPROVE_OPTION)
        {
            File selectedFile=file.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            jLabel11.setIcon(ResizeImage(path));
            JOptionPane.showMessageDialog(null,"Upload Dish Image Successfully");

        }
        else if(photo==JFileChooser.CANCEL_OPTION)
        {
            JOptionPane.showMessageDialog(null,"Failed");
        }
        jLabel11.setSize(120,100);
        setVisible(true);
    }//GEN-LAST:event_btnDish1ActionPerformed

    private void btnDish3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDish3ActionPerformed
        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter ("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int photo=file.showSaveDialog(null);

        if(photo==JFileChooser.APPROVE_OPTION)
        {
            File selectedFile=file.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            jLabel13.setIcon(ResizeImage2(path));
            JOptionPane.showMessageDialog(null,"Upload Dish Image Successfully");

        }
        else if(photo==JFileChooser.CANCEL_OPTION)
        {
            JOptionPane.showMessageDialog(null,"Failed");
        }
        jLabel13.setSize(120,100);
        setVisible(true);
    }//GEN-LAST:event_btnDish3ActionPerformed

    private void btnDish2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDish2ActionPerformed
        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter ("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int photo=file.showSaveDialog(null);

        if(photo==JFileChooser.APPROVE_OPTION)
        {
            File selectedFile=file.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            jLabel12.setIcon(ResizeImage(path));
            JOptionPane.showMessageDialog(null,"Upload Dish Image Successfully");

        }
        else if(photo==JFileChooser.CANCEL_OPTION)
        {
            JOptionPane.showMessageDialog(null,"Failed");
        }
        jLabel12.setSize(120,100);
        setVisible(true);
    }//GEN-LAST:event_btnDish2ActionPerformed

    private void btnDish5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDish5ActionPerformed
        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter ("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int photo=file.showSaveDialog(null);

        if(photo==JFileChooser.APPROVE_OPTION)
        {
            File selectedFile=file.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            jLabel15.setIcon(ResizeImage(path));
            JOptionPane.showMessageDialog(null,"Upload Dish Image Successfully");

        }
        else if(photo==JFileChooser.CANCEL_OPTION)
        {
            JOptionPane.showMessageDialog(null,"Failed");
        }
        jLabel15.setSize(120,100);
        setVisible(true);
    }//GEN-LAST:event_btnDish5ActionPerformed

    private void btnDish4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDish4ActionPerformed
        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter ("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int photo=file.showSaveDialog(null);

        if(photo==JFileChooser.APPROVE_OPTION)
        {
            File selectedFile=file.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            jLabel14.setIcon(ResizeImage(path));
            JOptionPane.showMessageDialog(null,"Upload Dish Image Successfully");

        }
        else if(photo==JFileChooser.CANCEL_OPTION)
        {
            JOptionPane.showMessageDialog(null,"Failed");
        }
        jLabel14.setSize(120,100);
        setVisible(true);
    }//GEN-LAST:event_btnDish4ActionPerformed

    private void btnDish6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDish6ActionPerformed
        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter ("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int photo=file.showSaveDialog(null);

        if(photo==JFileChooser.APPROVE_OPTION)
        {
            File selectedFile=file.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            jLabel16.setIcon(ResizeImage(path));
            JOptionPane.showMessageDialog(null,"Upload Dish Image Successfully");

        }
        else if(photo==JFileChooser.CANCEL_OPTION)
        {
            JOptionPane.showMessageDialog(null,"Failed");
        }
        jLabel16.setSize(120,100);
        setVisible(true);
    }//GEN-LAST:event_btnDish6ActionPerformed

    private void btnDish8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDish8ActionPerformed
        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter ("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int photo=file.showSaveDialog(null);

        if(photo==JFileChooser.APPROVE_OPTION)
        {
            File selectedFile=file.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            jLabel18.setIcon(ResizeImage(path));
            JOptionPane.showMessageDialog(null,"Upload Dish Image Successfully");

        }
        else if(photo==JFileChooser.CANCEL_OPTION)
        {
            JOptionPane.showMessageDialog(null,"Failed");
        }
        jLabel18.setSize(120,100);
        setVisible(true);
    }//GEN-LAST:event_btnDish8ActionPerformed

public ImageIcon ResizeImage (String ImagePath)
{
    ImageIcon image1 = new ImageIcon(ImagePath);
    Image image2 = image1.getImage();
    Image newImg=image2.getScaledInstance(jLabel11.getWidth(),jLabel11.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);  
    return image;
}

public ImageIcon ResizeImage2 (String ImagePath)
{
    ImageIcon image1 = new ImageIcon(ImagePath);
    Image image2 = image1.getImage();
    Image newImg=image2.getScaledInstance(jLabel12.getWidth(),jLabel12.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);  
    return image;
}

public ImageIcon ResizeImage3 (String ImagePath)
{
    ImageIcon image1 = new ImageIcon(ImagePath);
    Image image2 = image1.getImage();
    Image newImg=image2.getScaledInstance(jLabel13.getWidth(),jLabel13.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);  
    return image;
}

public ImageIcon ResizeImage4 (String ImagePath)
{
    ImageIcon image1 = new ImageIcon(ImagePath);
    Image image2 = image1.getImage();
    Image newImg=image2.getScaledInstance(jLabel14.getWidth(),jLabel14.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);  
    return image;
}

public ImageIcon ResizeImage5 (String ImagePath)
{
    ImageIcon image1 = new ImageIcon(ImagePath);
    Image image2 = image1.getImage();
    Image newImg=image2.getScaledInstance(jLabel15.getWidth(),jLabel15.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);  
    return image;
}

public ImageIcon ResizeImage6 (String ImagePath)
{
    ImageIcon image1 = new ImageIcon(ImagePath);
    Image image2 = image1.getImage();
    Image newImg=image2.getScaledInstance(jLabel16.getWidth(),jLabel16.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);  
    return image;
}

public ImageIcon ResizeImage7 (String ImagePath)
{
    ImageIcon image1 = new ImageIcon(ImagePath);
    Image image2 = image1.getImage();
    Image newImg=image2.getScaledInstance(jLabel17.getWidth(),jLabel17.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);  
    return image;
}

public ImageIcon ResizeImage8 (String ImagePath)
{
    ImageIcon image1 = new ImageIcon(ImagePath);
    Image image2 = image1.getImage();
    Image newImg=image2.getScaledInstance(jLabel18.getWidth(),jLabel18.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);  
    return image;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmBTN;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JButton backjButton2;
    private javax.swing.JButton btnDish1;
    private javax.swing.JButton btnDish2;
    private javax.swing.JButton btnDish3;
    private javax.swing.JButton btnDish4;
    private javax.swing.JButton btnDish5;
    private javax.swing.JButton btnDish6;
    private javax.swing.JButton btnDish7;
    private javax.swing.JButton btnDish8;
    private javax.swing.JTextField dish1JTextField;
    private javax.swing.JTextField dish2JTextField;
    private javax.swing.JTextField dish3JTextField;
    private javax.swing.JTextField dish4JTextField;
    private javax.swing.JTextField dish5JTextField;
    private javax.swing.JTextField dish6JTextField;
    private javax.swing.JTextField dish7JTextField;
    private javax.swing.JTextField dish8JTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel190;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel192;
    private javax.swing.JLabel jLabel193;
    private javax.swing.JLabel jLabel194;
    private javax.swing.JLabel jLabel195;
    private javax.swing.JLabel jLabel196;
    private javax.swing.JLabel jLabel197;
    private javax.swing.JLabel jLabel198;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JLabel jLabel215;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField price1JTextField;
    private javax.swing.JTextField price2JTextField;
    private javax.swing.JTextField price3JTextField;
    private javax.swing.JTextField price4JTextField;
    private javax.swing.JTextField price5JTextField;
    private javax.swing.JTextField price6JTextField;
    private javax.swing.JTextField price7JTextField;
    private javax.swing.JTextField price8JTextField;
    // End of variables declaration//GEN-END:variables
}
