/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Resturant;

import Business.AreYouHungrySystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Order.CustomerOrder;
import Business.Order.MenuOrder;
import Business.Order.Order;
import Business.Order.RequestOrder;
import Business.Order.TruckDriverOrder;
import Business.Organization.KitchenOrganization;
import Business.Organization.Organization;
import Business.Organization.TruckDriverOrganization;
import Business.UserAccount.UserAccount;
import Interface.Customer.CustomerRankJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SS
 */
public class RequestSupplyJPanel extends javax.swing.JPanel {
 private JPanel userProcessContainer;
    private UserAccount userAccount;
       private Enterprise enterprise;
    private KitchenOrganization kitchenOrganization;
    private DB4OUtil db4OUtil = DB4OUtil.getInstance();
private Network inNetwork;
    private Enterprise inEnterprise;
    private Organization inOrganization;
    private AreYouHungrySystem system;
    /**
     * Creates new form RequestSupplyJPanel
     */
    public RequestSupplyJPanel(JPanel userProcessContainer, UserAccount userAccount,KitchenOrganization kitchenOrganization, AreYouHungrySystem system,Enterprise enterprise) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
     this.enterprise=enterprise;
        this.userAccount = userAccount;
        this.system = system;
        this.kitchenOrganization=kitchenOrganization;
          inNetwork = null;
        inEnterprise = null;
        inOrganization = null;
        for(Network outNetwork: system.getNetworkList()){
            if(outNetwork.getName().equals("Boston")){
                inNetwork = outNetwork;
            }
        }
        
        for(Enterprise outEnterprise: inNetwork.getEnterpriseDirectory().getEnterpriseList()){
            if(outEnterprise.getEnterpriseType().toString().equals("Resturant")){
                inEnterprise = outEnterprise;
            }
        }
        
        for(Organization outOrganization: inEnterprise.getOrganizationDirectory().getOrganizationList()){
            //System.out.println(outOrganization.getName());
            if(outOrganization.getName().equals("Resturant Name")){
                inOrganization = outOrganization;
            }
        }
        
        //populateComboBox();
        populateTable();
        jLabel5.setText(userAccount.toString());
        
    }


    
     public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
       
        //userAccount.setOrderDirectory(new OrderDirectory());
        for (Order order : userAccount.getOrderDirectory().getOrderList()){
            Object[] row = new Object[4];
            
            row[0] = ((MenuOrder) order);
            if(((MenuOrder) order).getStatus()==1)
                    {
                    row[1] ="Waiting for truck driver";
                    }
            else if(((MenuOrder) order).getStatus()==2)
            {
                row[1] = "Truck driver on the way";
            }
            else if(((MenuOrder) order).getStatus()==3)
            {
                row[1] = "Truck driver arrived";
            }
             else if(((MenuOrder) order).getStatus()==-2)
            {
                row[1] = "Request rejected";
            }
            row[2] = ((MenuOrder) order).getSendDate();
            row[3] = ((MenuOrder) order).getTruck();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        backjButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel210 = new javax.swing.JLabel();
        jLabel211 = new javax.swing.JLabel();
        jLabel212 = new javax.swing.JLabel();
        jLabel213 = new javax.swing.JLabel();
        jLabel214 = new javax.swing.JLabel();
        jLabel215 = new javax.swing.JLabel();
        jLabel216 = new javax.swing.JLabel();
        jLabel217 = new javax.swing.JLabel();
        jLabel218 = new javax.swing.JLabel();
        jLabel219 = new javax.swing.JLabel();
        jLabel220 = new javax.swing.JLabel();
        jLabel221 = new javax.swing.JLabel();
        jLabel222 = new javax.swing.JLabel();
        jLabel223 = new javax.swing.JLabel();
        jLabel224 = new javax.swing.JLabel();
        jLabel225 = new javax.swing.JLabel();
        jLabel226 = new javax.swing.JLabel();
        jLabel227 = new javax.swing.JLabel();
        jLabel228 = new javax.swing.JLabel();
        jLabel229 = new javax.swing.JLabel();
        jLabel230 = new javax.swing.JLabel();
        jLabel231 = new javax.swing.JLabel();
        jLabel232 = new javax.swing.JLabel();
        jLabel233 = new javax.swing.JLabel();
        jLabel234 = new javax.swing.JLabel();
        jLabel235 = new javax.swing.JLabel();
        jLabel236 = new javax.swing.JLabel();
        jLabel237 = new javax.swing.JLabel();
        jLabel238 = new javax.swing.JLabel();
        jLabel239 = new javax.swing.JLabel();
        jLabel240 = new javax.swing.JLabel();
        jLabel241 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 167, 62));
        setLayout(null);

        jTextField1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(760, 450, 102, 28);

        backjButton2.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        backjButton2.setText("<< Back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });
        add(backjButton2);
        backjButton2.setBounds(1226, 49, 101, 44);

        jButton1.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(688, 655, 95, 49);

        jTable1.setBackground(new java.awt.Color(255, 102, 0));
        jTable1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Stuff", "Status", "Date", "Truck"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(330, 205, 725, 136);

        jLabel2.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel2.setText("Stuff");
        add(jLabel2);
        jLabel2.setBounds(520, 460, 49, 24);

        jLabel1.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        jLabel1.setText("Request List");
        add(jLabel1);
        jLabel1.setBounds(635, 133, 160, 31);

        btnAccept.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        btnAccept.setText("Delivery Confirm");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept);
        btnAccept.setBounds(859, 359, 196, 56);

        jLabel3.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel3.setText("Quantity");
        add(jLabel3);
        jLabel3.setBounds(520, 530, 84, 24);

        jTextField2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(jTextField2);
        jTextField2.setBounds(760, 530, 102, 28);

        jLabel33.setFont(new java.awt.Font("Nanum Brush Script", 1, 80)); // NOI18N
        jLabel33.setText("Are You Hungry");
        add(jLabel33);
        jLabel33.setBounds(556, 0, 403, 93);

        jLabel8.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel8.setText("Take-Away Service");
        add(jLabel8);
        jLabel8.setBounds(971, 64, 155, 29);

        jLabel14.setFont(new java.awt.Font("Wingdings 3", 0, 36)); // NOI18N
        jLabel14.setText("c");
        add(jLabel14);
        jLabel14.setBounds(660, 520, 34, 33);

        jLabel15.setFont(new java.awt.Font("Wingdings 3", 0, 36)); // NOI18N
        jLabel15.setText("c");
        add(jLabel15);
        jLabel15.setBounds(660, 450, 34, 33);

        jLabel4.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel4.setText("Restaurant");
        add(jLabel4);
        jLabel4.setBounds(261, 133, 109, 24);

        jLabel5.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        jLabel5.setText("Res");
        add(jLabel5);
        jLabel5.setBounds(408, 137, 71, 19);

        jLabel6.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        jLabel6.setText("KG");
        add(jLabel6);
        jLabel6.setBounds(880, 520, 37, 36);

        jLabel210.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel210.setText("h");
        add(jLabel210);
        jLabel210.setBounds(120, 190, 19, 20);

        jLabel211.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel211.setText("h");
        add(jLabel211);
        jLabel211.setBounds(430, 40, 19, 20);

        jLabel212.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel212.setText("h");
        add(jLabel212);
        jLabel212.setBounds(60, 50, 19, 20);

        jLabel213.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel213.setText("h");
        add(jLabel213);
        jLabel213.setBounds(120, 430, 19, 20);

        jLabel214.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel214.setText("h");
        add(jLabel214);
        jLabel214.setBounds(210, 70, 19, 20);

        jLabel215.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel215.setText("h");
        add(jLabel215);
        jLabel215.setBounds(290, 490, 19, 20);

        jLabel216.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel216.setText("h");
        add(jLabel216);
        jLabel216.setBounds(450, 380, 19, 20);

        jLabel217.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel217.setText("h");
        add(jLabel217);
        jLabel217.setBounds(130, 570, 19, 20);

        jLabel218.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel218.setText("h");
        add(jLabel218);
        jLabel218.setBounds(890, 610, 19, 20);

        jLabel219.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel219.setText("h");
        add(jLabel219);
        jLabel219.setBounds(80, 330, 19, 20);

        jLabel220.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel220.setText("h");
        add(jLabel220);
        jLabel220.setBounds(210, 290, 19, 20);

        jLabel221.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel221.setText("h");
        add(jLabel221);
        jLabel221.setBounds(700, 380, 19, 20);

        jLabel222.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel222.setText("h");
        add(jLabel222);
        jLabel222.setBounds(270, 660, 19, 20);

        jLabel223.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel223.setText("h");
        add(jLabel223);
        jLabel223.setBounds(590, 740, 19, 20);

        jLabel224.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel224.setText("h");
        add(jLabel224);
        jLabel224.setBounds(1050, 540, 19, 20);

        jLabel225.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel225.setText("h");
        add(jLabel225);
        jLabel225.setBounds(770, 780, 19, 20);

        jLabel226.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel226.setText("h");
        add(jLabel226);
        jLabel226.setBounds(620, 600, 19, 20);

        jLabel227.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel227.setText("h");
        add(jLabel227);
        jLabel227.setBounds(100, 710, 19, 20);

        jLabel228.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel228.setText("h");
        add(jLabel228);
        jLabel228.setBounds(380, 760, 19, 20);

        jLabel229.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel229.setText("h");
        add(jLabel229);
        jLabel229.setBounds(420, 600, 19, 20);

        jLabel230.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel230.setText("h");
        add(jLabel230);
        jLabel230.setBounds(1200, 730, 19, 20);

        jLabel231.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel231.setText("h");
        add(jLabel231);
        jLabel231.setBounds(1230, 320, 19, 20);

        jLabel232.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel232.setText("h");
        add(jLabel232);
        jLabel232.setBounds(1130, 630, 19, 20);

        jLabel233.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel233.setText("h");
        add(jLabel233);
        jLabel233.setBounds(1030, 800, 19, 20);

        jLabel234.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel234.setText("h");
        add(jLabel234);
        jLabel234.setBounds(960, 700, 19, 20);

        jLabel235.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel235.setText("h");
        add(jLabel235);
        jLabel235.setBounds(810, 90, 19, 20);

        jLabel236.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel236.setText("h");
        add(jLabel236);
        jLabel236.setBounds(1230, 490, 19, 20);

        jLabel237.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel237.setText("h");
        add(jLabel237);
        jLabel237.setBounds(1280, 120, 19, 20);

        jLabel238.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel238.setText("h");
        add(jLabel238);
        jLabel238.setBounds(1160, 230, 19, 20);

        jLabel239.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel239.setText("h");
        add(jLabel239);
        jLabel239.setBounds(1140, 130, 19, 20);

        jLabel240.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel240.setText("h");
        add(jLabel240);
        jLabel240.setBounds(1130, 10, 19, 20);

        jLabel241.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel241.setText("h");
        add(jLabel241);
        jLabel241.setBounds(940, 130, 19, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        String content =  jTextField1.getText();
        String quantity = jTextField2.getText()+"KG";
        jTextField1.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel2.setForeground(Color.BLACK);
        jTextField2.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel3.setForeground(Color.BLACK);
        
        if(content==null||content.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Content cannot be empty!");
            jTextField1.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel2.setForeground(Color.RED);
            return;
        }
           try{
            Integer.parseInt(jTextField2.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please input a valid quantity!");
             jTextField2.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel3.setForeground(Color.RED);
            return;
        }
        String Content=content+"*"+quantity;
        SimpleDateFormat sdf = new SimpleDateFormat();
        sdf.applyPattern("yyyy-MM-dd HH:mm:ss a"); 
        
        Date date = new Date();

        String resturantName = "";
       
       if(jLabel5.getText() != null){
            resturantName = jLabel5.getText();
//            for(UserAccount ua : inOrganization.getUserAccountDirectory().getUserAccountList()){
//                if(ua.getUsername().equals(resturantName)){
                    for(Order menuOrder : userAccount.getOrderDirectory().getOrderList()){
                        String dish1=(((MenuOrder) menuOrder).getDish1());
                        String dish2=(((MenuOrder) menuOrder).getDish2());
                        String dish3=(((MenuOrder) menuOrder).getDish3());
                        String dish4=(((MenuOrder) menuOrder).getDish4());
                        String dish5=(((MenuOrder) menuOrder).getDish5());
                        String dish6=(((MenuOrder) menuOrder).getDish6());
                        String dish7=(((MenuOrder) menuOrder).getDish7());
                        String dish8=(((MenuOrder) menuOrder).getDish8());

                        Double price1=(((MenuOrder) menuOrder).getPrice1());
                        Double price2=(((MenuOrder) menuOrder).getPrice2());
                        Double price3=(((MenuOrder) menuOrder).getPrice3());
                        Double price4=(((MenuOrder) menuOrder).getPrice4());
                        Double price5=(((MenuOrder) menuOrder).getPrice5());
                        Double price6=(((MenuOrder) menuOrder).getPrice6());
                        Double price7=(((MenuOrder) menuOrder).getPrice7());
                        Double price8=(((MenuOrder) menuOrder).getPrice8());

                        ImageIcon Image1=( ((MenuOrder) menuOrder).getDish11());
                        ImageIcon Image2=( ((MenuOrder) menuOrder).getDish12());
                        ImageIcon Image3=( ((MenuOrder) menuOrder).getDish13());
                        ImageIcon Image4=( ((MenuOrder) menuOrder).getDish14());
                        ImageIcon Image5=( ((MenuOrder) menuOrder).getDish15());
                        ImageIcon Image6=( ((MenuOrder) menuOrder).getDish16());
                        ImageIcon Image7=( ((MenuOrder) menuOrder).getDish17());
                        ImageIcon Image8=( ((MenuOrder) menuOrder).getDish18());
 
        MenuOrder order = new MenuOrder();
        order.setContent(Content);
        order.setStatus(1);
        order.setSendDate(date);
        order.setResName(userAccount.toString());
        
        order.setDish1(dish1);
        order.setDish2(dish2);
        order.setDish3(dish3);
        order.setDish4(dish4);
        order.setDish5(dish5);
        order.setDish6(dish6);
        order.setDish7(dish7);
        order.setDish8(dish8);
        
        order.setPrice1(price1);
        order.setPrice2(price2);
        order.setPrice3(price3);
        order.setPrice4(price4);
        order.setPrice5(price5);
        order.setPrice6(price6);
        order.setPrice7(price7);
        order.setPrice8(price8);
        
        order.setDish11(Image1);
        order.setDish12(Image2);
        order.setDish13(Image3);
        order.setDish14(Image4);
        order.setDish15(Image5);
        order.setDish16(Image6);
        order.setDish17(Image7);
        order.setDish18(Image8);
                                                 
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof KitchenOrganization){
                org = organization;
                break;
            }
        }
        if(org != null){
            //org.getOrderDirectory().getOrderList().add(order);
            userAccount.getOrderDirectory().getOrderList().add(order);
                    }
             //   }
           // }
            
            populateTable();
        }
       jTextField1.setText("");
       jTextField2.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow>=0){
            MenuOrder order = (MenuOrder)jTable1.getValueAt(selectedRow, 0);
            if(order.getStatus() ==2){
                int selectionButton = JOptionPane.YES_NO_OPTION;
                int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure the materials have arrived???","Warning",selectionButton);
                if(selectionResult == JOptionPane.YES_OPTION){
                    SimpleDateFormat sdf = new SimpleDateFormat();
                    sdf.applyPattern("yyyy-MM-dd HH:mm:ss a"); 
                    Date date = new Date();
                    order.setStatus(3);
                    order.setSendDate(date);
                    
                    db4OUtil.storeSystem(system);
                    
                    populateTable();
                    JOptionPane.showMessageDialog(null, "Request confirmed!!");
                }
                 
                
            }else{
                JOptionPane.showMessageDialog(null, "You cannot Confirm this request!!!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_btnAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton2;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JLabel jLabel215;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JLabel jLabel218;
    private javax.swing.JLabel jLabel219;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel221;
    private javax.swing.JLabel jLabel222;
    private javax.swing.JLabel jLabel223;
    private javax.swing.JLabel jLabel224;
    private javax.swing.JLabel jLabel225;
    private javax.swing.JLabel jLabel226;
    private javax.swing.JLabel jLabel227;
    private javax.swing.JLabel jLabel228;
    private javax.swing.JLabel jLabel229;
    private javax.swing.JLabel jLabel230;
    private javax.swing.JLabel jLabel231;
    private javax.swing.JLabel jLabel232;
    private javax.swing.JLabel jLabel233;
    private javax.swing.JLabel jLabel234;
    private javax.swing.JLabel jLabel235;
    private javax.swing.JLabel jLabel236;
    private javax.swing.JLabel jLabel237;
    private javax.swing.JLabel jLabel238;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JLabel jLabel241;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
