/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Resturant;

import Interface.Customer.*;
import Business.AreYouHungrySystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Order.Order;
import Business.Order.TruckDriverOrder;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tczho
 */
public class ResturantSupplierCheckJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private AreYouHungrySystem system;
    private DB4OUtil db4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form ResturantSupplierCheck
     */
    ResturantSupplierCheckJPanel(JPanel userProcessContainer, UserAccount userAccount, AreYouHungrySystem system) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) DailyDeliveryJTable.getModel();
        model.setRowCount(0);
        
        Network inNetwork = null;
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        for(Network network : system.getNetworkList()){
            inNetwork = network;
        }
        for(Enterprise outEnterprise : inNetwork.getEnterpriseDirectory().getEnterpriseList()){
            if(outEnterprise.getEnterpriseType().toString().equals("Supplier")){
                inEnterprise = outEnterprise;
            }
        }
        
        for(Organization outOrganization: inEnterprise.getOrganizationDirectory().getOrganizationList()){
            //System.out.println(outOrganization.getName());
            if(outOrganization.getName().equals("Truck Driver")){
                inOrganization = outOrganization;
            }
        }
       
        //userAccount.setOrderDirectory(new OrderDirectory());
        for (UserAccount outUserAccount : inOrganization.getUserAccountDirectory().getUserAccountList()){
            for(Order order : outUserAccount.getOrderDirectory().getOrderList()){
                Object[] row = new Object[3];
            
                row[0] = ((TruckDriverOrder) order);
                row[1] = ((TruckDriverOrder) order).getDeliveryContent();
                row[2] = order.getOrderCompleteDate();

                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backjButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DailyDeliveryJTable = new javax.swing.JTable();
        ConfirmBTN = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel216 = new javax.swing.JLabel();
        jLabel217 = new javax.swing.JLabel();
        jLabel218 = new javax.swing.JLabel();
        jLabel219 = new javax.swing.JLabel();
        jLabel220 = new javax.swing.JLabel();
        jLabel221 = new javax.swing.JLabel();
        jLabel222 = new javax.swing.JLabel();
        jLabel223 = new javax.swing.JLabel();
        jLabel224 = new javax.swing.JLabel();
        jLabel225 = new javax.swing.JLabel();
        jLabel226 = new javax.swing.JLabel();
        jLabel227 = new javax.swing.JLabel();
        jLabel228 = new javax.swing.JLabel();
        jLabel229 = new javax.swing.JLabel();
        jLabel230 = new javax.swing.JLabel();
        jLabel231 = new javax.swing.JLabel();
        jLabel232 = new javax.swing.JLabel();
        jLabel233 = new javax.swing.JLabel();
        jLabel234 = new javax.swing.JLabel();
        jLabel235 = new javax.swing.JLabel();
        jLabel236 = new javax.swing.JLabel();
        jLabel237 = new javax.swing.JLabel();
        jLabel238 = new javax.swing.JLabel();
        jLabel239 = new javax.swing.JLabel();
        jLabel240 = new javax.swing.JLabel();
        jLabel241 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 167, 62));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Silom", 0, 24)); // NOI18N
        jLabel1.setText("Purchase List");
        add(jLabel1);
        jLabel1.setBounds(567, 125, 237, 49);

        backjButton1.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1);
        backjButton1.setBounds(1108, 49, 114, 44);

        DailyDeliveryJTable.setBackground(new java.awt.Color(255, 102, 0));
        DailyDeliveryJTable.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        DailyDeliveryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Resturant", "Stuff", "Confirm Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DailyDeliveryJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(278, 227, 741, 134);

        ConfirmBTN.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        ConfirmBTN.setText("Confirm Delivered");
        ConfirmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBTNActionPerformed(evt);
            }
        });
        add(ConfirmBTN);
        ConfirmBTN.setBounds(551, 414, 220, 50);

        jLabel33.setFont(new java.awt.Font("Nanum Brush Script", 1, 80)); // NOI18N
        jLabel33.setText("Are You Hungry");
        add(jLabel33);
        jLabel33.setBounds(463, 0, 403, 93);

        jLabel5.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel5.setText("zzzzzzzzzzz");
        add(jLabel5);
        jLabel5.setBounds(843, 200, 176, 21);

        jLabel6.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel6.setText("zzzzzzzzzzz");
        add(jLabel6);
        jLabel6.setBounds(278, 367, 176, 21);

        jLabel7.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel7.setText("Take-Away Service");
        add(jLabel7);
        jLabel7.setBounds(878, 64, 155, 29);

        jLabel216.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel216.setText("h");
        add(jLabel216);
        jLabel216.setBounds(820, 410, 19, 20);

        jLabel217.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel217.setText("h");
        add(jLabel217);
        jLabel217.setBounds(100, 440, 19, 20);

        jLabel218.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel218.setText("h");
        add(jLabel218);
        jLabel218.setBounds(180, 250, 19, 20);

        jLabel219.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel219.setText("h");
        add(jLabel219);
        jLabel219.setBounds(280, 30, 19, 21);

        jLabel220.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel220.setText("h");
        add(jLabel220);
        jLabel220.setBounds(70, 50, 19, 21);

        jLabel221.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel221.setText("h");
        add(jLabel221);
        jLabel221.setBounds(230, 510, 19, 21);

        jLabel222.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel222.setText("h");
        add(jLabel222);
        jLabel222.setBounds(1370, 370, 19, 21);

        jLabel223.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel223.setText("h");
        add(jLabel223);
        jLabel223.setBounds(880, 530, 19, 21);

        jLabel224.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel224.setText("h");
        add(jLabel224);
        jLabel224.setBounds(380, 450, 19, 21);

        jLabel225.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel225.setText("h");
        add(jLabel225);
        jLabel225.setBounds(1270, 280, 19, 21);

        jLabel226.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel226.setText("h");
        add(jLabel226);
        jLabel226.setBounds(1280, 70, 19, 21);

        jLabel227.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel227.setText("h");
        add(jLabel227);
        jLabel227.setBounds(970, 460, 19, 21);

        jLabel228.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel228.setText("h");
        add(jLabel228);
        jLabel228.setBounds(1000, 130, 19, 21);

        jLabel229.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel229.setText("h");
        add(jLabel229);
        jLabel229.setBounds(1120, 400, 19, 21);

        jLabel230.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel230.setText("h");
        add(jLabel230);
        jLabel230.setBounds(1390, 190, 19, 21);

        jLabel231.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel231.setText("h");
        add(jLabel231);
        jLabel231.setBounds(1290, 170, 19, 21);

        jLabel232.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel232.setText("h");
        add(jLabel232);
        jLabel232.setBounds(1410, 540, 19, 21);

        jLabel233.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel233.setText("h");
        add(jLabel233);
        jLabel233.setBounds(1230, 460, 19, 21);

        jLabel234.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel234.setText("h");
        add(jLabel234);
        jLabel234.setBounds(820, 110, 19, 21);

        jLabel235.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel235.setText("h");
        add(jLabel235);
        jLabel235.setBounds(1110, 230, 19, 21);

        jLabel236.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel236.setText("h");
        add(jLabel236);
        jLabel236.setBounds(380, 160, 19, 21);

        jLabel237.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel237.setText("h");
        add(jLabel237);
        jLabel237.setBounds(1120, 600, 19, 21);

        jLabel238.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel238.setText("h");
        add(jLabel238);
        jLabel238.setBounds(110, 590, 19, 21);

        jLabel239.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel239.setText("h");
        add(jLabel239);
        jLabel239.setBounds(660, 550, 19, 21);

        jLabel240.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel240.setText("h");
        add(jLabel240);
        jLabel240.setBounds(430, 590, 19, 21);

        jLabel241.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel241.setText("h");
        add(jLabel241);
        jLabel241.setBounds(170, 130, 19, 21);
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void ConfirmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBTNActionPerformed
        int selectedRow = DailyDeliveryJTable.getSelectedRow();
        if(selectedRow>=0){
            Order order = (Order)DailyDeliveryJTable.getValueAt(selectedRow, 0);
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure today's supply has been reached???","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                SimpleDateFormat sdf = new SimpleDateFormat();
                sdf.applyPattern("yyyy-MM-dd HH:mm:ss a"); 
                Date date = new Date();
                order.setOrderCompleteDate(date);
                    
                populateTable();
                db4OUtil.storeSystem(system);
                JOptionPane.showMessageDialog(null, "You have successfully confirm today's supply!!!");
                }
            
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_ConfirmBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmBTN;
    private javax.swing.JTable DailyDeliveryJTable;
    private javax.swing.JButton backjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JLabel jLabel218;
    private javax.swing.JLabel jLabel219;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel221;
    private javax.swing.JLabel jLabel222;
    private javax.swing.JLabel jLabel223;
    private javax.swing.JLabel jLabel224;
    private javax.swing.JLabel jLabel225;
    private javax.swing.JLabel jLabel226;
    private javax.swing.JLabel jLabel227;
    private javax.swing.JLabel jLabel228;
    private javax.swing.JLabel jLabel229;
    private javax.swing.JLabel jLabel230;
    private javax.swing.JLabel jLabel231;
    private javax.swing.JLabel jLabel232;
    private javax.swing.JLabel jLabel233;
    private javax.swing.JLabel jLabel234;
    private javax.swing.JLabel jLabel235;
    private javax.swing.JLabel jLabel236;
    private javax.swing.JLabel jLabel237;
    private javax.swing.JLabel jLabel238;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JLabel jLabel241;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
