/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DeliveryPlatform;

import Business.AreYouHungrySystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Order.CustomerOrder;
import Business.Order.Order;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tczho
 */
public class DeliverymanJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private AreYouHungrySystem system;
    private DB4OUtil db4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form DeliverymanJPanel
     */
    public DeliverymanJPanel(JPanel userProcessContainer, UserAccount userAccount, AreYouHungrySystem system) {
        initComponents();
        this.userAccount = userAccount;
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) needDeliveryTBL.getModel();
        model.setRowCount(0);
       
        Network inNetwork = null;
        Enterprise inEnterprise = null;
        for(Network network : system.getNetworkList()){
            inNetwork = network;
        }
        for(Enterprise outEnterprise : inNetwork.getEnterpriseDirectory().getEnterpriseList()){
            if(outEnterprise.getEnterpriseType().toString().equals("Customer")){
                inEnterprise = outEnterprise;
            }
        }
        for(UserAccount outUserAccount : inEnterprise.getUserAccountDirectory().getUserAccountList()){
            for(Order order : outUserAccount.getOrderDirectory().getOrderList()){
                if(((CustomerOrder) order).getStatus() == 2 || ((CustomerOrder) order).getStatus() == 3){
                    Object[] row = new Object[5];

                    row[0] = ((CustomerOrder) order);
                    row[1] = order.getSender();
                    row[2] = order.getOrderStartDate();
                    row[3] = order.getOrderContent();
                    if(order.getStatus() == 2){
                        row[4] = "Waiting for deliveryman";
                    }else if(order.getStatus() == 3){
                        row[4] = "Waiting for customer to confirm";
                    }
                    model.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        needDeliveryTBL = new javax.swing.JTable();
        deliverOrderBTN = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 167, 62));
        setLayout(null);

        needDeliveryTBL.setBackground(new java.awt.Color(255, 102, 0));
        needDeliveryTBL.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        needDeliveryTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Resturant", "Customer Name", "Order Date", "Dishes", "Order Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(needDeliveryTBL);

        add(jScrollPane1);
        jScrollPane1.setBounds(230, 204, 899, 132);

        deliverOrderBTN.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        deliverOrderBTN.setText("Deliver");
        deliverOrderBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverOrderBTNActionPerformed(evt);
            }
        });
        add(deliverOrderBTN);
        deliverOrderBTN.setBounds(610, 384, 130, 50);

        jLabel33.setFont(new java.awt.Font("Nanum Brush Script", 1, 80)); // NOI18N
        jLabel33.setText("Are You Hungry");
        add(jLabel33);
        jLabel33.setBounds(463, 0, 403, 93);

        jLabel7.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel7.setText("Take-Away Service");
        add(jLabel7);
        jLabel7.setBounds(878, 64, 155, 29);

        jLabel1.setFont(new java.awt.Font("Silom", 0, 24)); // NOI18N
        jLabel1.setText("Deliveryman Order History");
        add(jLabel1);
        jLabel1.setBounds(524, 133, 342, 31);

        jLabel3.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel3.setText("zzzzzzzzzzz");
        add(jLabel3);
        jLabel3.setBounds(953, 177, 176, 21);

        jLabel4.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel4.setText("zzzzzzzzzzz");
        add(jLabel4);
        jLabel4.setBounds(230, 342, 176, 21);

        jLabel126.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel126.setText("h");
        add(jLabel126);
        jLabel126.setBounds(110, 80, 19, 20);

        jLabel127.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel127.setText("h");
        add(jLabel127);
        jLabel127.setBounds(110, 420, 19, 20);

        jLabel128.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel128.setText("h");
        add(jLabel128);
        jLabel128.setBounds(440, 100, 19, 20);

        jLabel129.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel129.setText("h");
        add(jLabel129);
        jLabel129.setBounds(240, 30, 19, 20);

        jLabel130.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel130.setText("h");
        add(jLabel130);
        jLabel130.setBounds(270, 120, 19, 20);

        jLabel131.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel131.setText("h");
        add(jLabel131);
        jLabel131.setBounds(80, 590, 19, 20);

        jLabel132.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel132.setText("h");
        add(jLabel132);
        jLabel132.setBounds(140, 240, 19, 20);

        jLabel133.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel133.setText("h");
        add(jLabel133);
        jLabel133.setBounds(670, 540, 19, 20);

        jLabel134.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel134.setText("h");
        add(jLabel134);
        jLabel134.setBounds(380, 460, 19, 20);

        jLabel135.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel135.setText("h");
        add(jLabel135);
        jLabel135.setBounds(1060, 100, 19, 20);

        jLabel136.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel136.setText("h");
        add(jLabel136);
        jLabel136.setBounds(480, 570, 19, 20);

        jLabel137.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel137.setText("h");
        add(jLabel137);
        jLabel137.setBounds(1000, 530, 19, 20);

        jLabel138.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel138.setText("h");
        add(jLabel138);
        jLabel138.setBounds(850, 440, 19, 20);

        jLabel139.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel139.setText("h");
        add(jLabel139);
        jLabel139.setBounds(1390, 430, 19, 20);

        jLabel140.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel140.setText("h");
        add(jLabel140);
        jLabel140.setBounds(1040, 430, 19, 20);

        jLabel141.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel141.setText("h");
        add(jLabel141);
        jLabel141.setBounds(1370, 130, 19, 20);

        jLabel142.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel142.setText("h");
        add(jLabel142);
        jLabel142.setBounds(1210, 40, 19, 20);

        jLabel143.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel143.setText("h");
        add(jLabel143);
        jLabel143.setBounds(1230, 370, 19, 20);

        jLabel144.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel144.setText("h");
        add(jLabel144);
        jLabel144.setBounds(310, 710, 19, 20);

        jLabel145.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel145.setText("h");
        add(jLabel145);
        jLabel145.setBounds(260, 540, 19, 20);

        jLabel146.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel146.setText("h");
        add(jLabel146);
        jLabel146.setBounds(1380, 290, 19, 20);

        jLabel147.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel147.setText("h");
        add(jLabel147);
        jLabel147.setBounds(1230, 200, 19, 20);

        jLabel148.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel148.setText("h");
        add(jLabel148);
        jLabel148.setBounds(1440, 650, 19, 20);

        jLabel149.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel149.setText("h");
        add(jLabel149);
        jLabel149.setBounds(830, 640, 19, 20);

        jLabel150.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel150.setText("h");
        add(jLabel150);
        jLabel150.setBounds(1260, 530, 19, 20);

        jLabel151.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel151.setText("h");
        add(jLabel151);
        jLabel151.setBounds(1160, 640, 19, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void deliverOrderBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverOrderBTNActionPerformed
        int selectedRow = needDeliveryTBL.getSelectedRow();
        if(selectedRow>=0){
            Order order = (Order)needDeliveryTBL.getValueAt(selectedRow, 0);
            if(order.getStatus() ==2){
                int selectionButton = JOptionPane.YES_NO_OPTION;
                int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to deliver this order???","Warning",selectionButton);
                if(selectionResult == JOptionPane.YES_OPTION){
                    order.setStatus(3);
                    order.setReceiver(userAccount);
                    populateTable();
                    db4OUtil.storeSystem(system);
                    
                    JOptionPane.showMessageDialog(null, "You have successfully accept this order's delivery work!!!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "You cannot accept this Order!!!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_deliverOrderBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deliverOrderBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable needDeliveryTBL;
    // End of variables declaration//GEN-END:variables
}
