/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.NormalAdmin;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tczho
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    /**
     * Creates new form ManageOrganizationJPanel
     */

    ManageOrganizationJPanel(JPanel userProcessContainer, OrganizationDirectory organizationDirectory, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.directory = organizationDirectory;
        this.enterprise = enterprise;
        
        populateTable();
        populateCombo();
    }
    
    private void populateCombo(){
        organizationJComboBox.removeAllItems();
        for (Organization.Type type : Organization.Type.values()){
            if(enterprise.getEnterpriseType().getValue().equals("Supplier")){
                organizationJComboBox.addItem(type.TruckDriver);
                organizationJComboBox.addItem(type.Warehouse);
                break;
            }else if(enterprise.getEnterpriseType().getValue().equals("Resturant")){
                organizationJComboBox.addItem(type.ResturantName);
                organizationJComboBox.addItem(type.OrderTaker);
                break;
            }else if(enterprise.getEnterpriseType().getValue().equals("DeliveryPlatform")){
                organizationJComboBox.addItem(type.DeliveryPlatformOrderTaker);
                organizationJComboBox.addItem(type.Deliveryman);
                break;
            }else if(enterprise.getEnterpriseType().getValue().equals("Customer")){
                organizationJComboBox.addItem(type.Customer);
                break;
            }
        }
    }

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        
        model.setRowCount(0);
        
        for (Organization organization : directory.getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        addJButton = new javax.swing.JButton();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 167, 62));
        jPanel1.setLayout(null);

        organizationJTable.setBackground(new java.awt.Color(255, 102, 0));
        organizationJTable.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(421, 207, 480, 92);

        addJButton.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        addJButton.setText("Submit");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addJButton);
        addJButton.setBounds(620, 420, 96, 45);

        organizationJComboBox.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(organizationJComboBox);
        organizationJComboBox.setBounds(730, 340, 134, 35);

        jLabel1.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel1.setText("Organization Type ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 350, 181, 24);

        backJButton.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton);
        backJButton.setBounds(1109, 54, 97, 45);

        jLabel33.setFont(new java.awt.Font("Nanum Brush Script", 1, 80)); // NOI18N
        jLabel33.setText("Are You Hungry");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(462, 6, 403, 93);

        jLabel2.setFont(new java.awt.Font("Silom", 0, 24)); // NOI18N
        jLabel2.setText("Manage Organization");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(542, 136, 278, 31);

        jLabel7.setFont(new java.awt.Font("Nanum Brush Script", 0, 24)); // NOI18N
        jLabel7.setText("Take-Away Service");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(877, 70, 155, 29);

        jLabel14.setFont(new java.awt.Font("Wingdings 3", 0, 36)); // NOI18N
        jLabel14.setText("c");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(650, 340, 34, 42);

        jLabel142.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel142.setText("h");
        jPanel1.add(jLabel142);
        jLabel142.setBounds(980, 160, 19, 20);

        jLabel143.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel143.setText("h");
        jPanel1.add(jLabel143);
        jLabel143.setBounds(1240, 450, 19, 20);

        jLabel144.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel144.setText("h");
        jPanel1.add(jLabel144);
        jLabel144.setBounds(410, 140, 19, 20);

        jLabel145.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel145.setText("h");
        jPanel1.add(jLabel145);
        jLabel145.setBounds(1050, 480, 19, 20);

        jLabel146.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel146.setText("h");
        jPanel1.add(jLabel146);
        jLabel146.setBounds(760, 590, 19, 20);

        jLabel147.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel147.setText("h");
        jPanel1.add(jLabel147);
        jLabel147.setBounds(90, 70, 19, 20);

        jLabel148.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel148.setText("h");
        jPanel1.add(jLabel148);
        jLabel148.setBounds(1020, 340, 19, 20);

        jLabel149.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel149.setText("h");
        jPanel1.add(jLabel149);
        jLabel149.setBounds(160, 360, 19, 20);

        jLabel150.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel150.setText("h");
        jPanel1.add(jLabel150);
        jLabel150.setBounds(510, 550, 19, 20);

        jLabel151.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel151.setText("h");
        jPanel1.add(jLabel151);
        jLabel151.setBounds(170, 510, 19, 20);

        jLabel152.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel152.setText("h");
        jPanel1.add(jLabel152);
        jLabel152.setBounds(320, 320, 19, 20);

        jLabel153.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel153.setText("h");
        jPanel1.add(jLabel153);
        jLabel153.setBounds(300, 570, 19, 20);

        jLabel154.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel154.setText("h");
        jPanel1.add(jLabel154);
        jLabel154.setBounds(370, 460, 19, 20);

        jLabel155.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel155.setText("h");
        jPanel1.add(jLabel155);
        jLabel155.setBounds(310, 30, 19, 20);

        jLabel156.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel156.setText("h");
        jPanel1.add(jLabel156);
        jLabel156.setBounds(210, 190, 19, 20);

        jLabel157.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel157.setText("h");
        jPanel1.add(jLabel157);
        jLabel157.setBounds(1260, 180, 20, 20);

        jLabel158.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel158.setText("h");
        jPanel1.add(jLabel158);
        jLabel158.setBounds(1320, 320, 20, 20);

        jLabel159.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel159.setText("h");
        jPanel1.add(jLabel159);
        jLabel159.setBounds(960, 20, 20, 20);

        jLabel160.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel160.setText("h");
        jPanel1.add(jLabel160);
        jLabel160.setBounds(1190, 580, 19, 20);

        jLabel161.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel161.setText("h");
        jPanel1.add(jLabel161);
        jLabel161.setBounds(1170, 310, 19, 20);

        jLabel162.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel162.setText("h");
        jPanel1.add(jLabel162);
        jLabel162.setBounds(860, 500, 19, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1365, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1365, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

        Type type = (Type) organizationJComboBox.getSelectedItem();
        directory.createOrganization(type);
        populateTable();
    }//GEN-LAST:event_addJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTable organizationJTable;
    // End of variables declaration//GEN-END:variables
}
